---
title: "Book"
output:
  html_document:
    theme: cerulean
    toc: true
    toc_float: true
    collapsed: false
    number_sections: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Recommended readings to everyone who is interested about microeconomics, public economics, environmental economics, econometrics, international economics, human geography, experimental economics, spatial economics, data science and energy economics.

### Microeconomics

1.  Kreps, D. (2013). Microeconomic foundations I: Choice and competitive markets. Princeton University Press.

2.  Kreps, D. (2023). Microeconomic foundations II: Imperfect competition, information, and strategic interaction. Princeton University Press.

3.  Cameron, A. and Trivedi, P. (2005) Microeconometrics: Methods and applications. Cambridge University Press, New York.

4.  Nicholson, W., and Snyder, C. (2016). Microeconomic theory: Basic principles and extension (12th Edition). Cengage Learning.

5.  Varian, H. (2016). Intermediate microeconomics: A modern approach (9th Edition). WW Norton & Company.

### Public Economics

1. Gruber, J. (2018). Public finance and public policy (6th Edition), Worth Publishers.

2. Stiglitz, J., and Rosengard, J. (2015). Economics of the public sector (6th Edition). WW Norton & Company.

### Environmental Economics

1.  Kolstad, C. (2011), Environmental economics. New York : Oxford University Press.

2.  Tietenberg, T., and Lewis, L. (2019). Environmental and natural resource economics (11th Edition). Routledge.

### Econometrics

1.  Wooldridge, J. (2019) Introductory econometrics: A modern approach. Cengage Learning.

2.  Wooldridge, J. (2010) Econometric analysis of cross section and panel data. MIT press.

3.  Angrist, J. and Pischke, J. (2009) Mostly harmless econometrics: An empiricist's companion. Princeton University Press.

4.  Cameron, C. and Trivedi, P. (2022) Volume I: Cross-sectional and panel regression methods. Stata Press.

5.  Cameron, C. and Trivedi, P. (2022) Volume II: Nonlinear models and causal inference methods. Stata Press.

### International Economics

1. Krugman, P., Obstfeld, M., and Melitz, M. (2018). International economics: Theory and policy. Boston: Pearson Education

2. Krugman, P., Obstfeld, M., and Melitz, M. (2017). International trade: Theory and policy. Boston: Pearson Education

3. Krugman, P., Obstfeld, M., and Melitz, M. (2018). International finance: Theory and policy. Boston: Pearson Education

### Human Geography

1. Fouberg, E., Murphy, A., and De Blij, H. (2020). Human geography: People, place, and culture. (12th Edition). Wiley.

2. Knox, P., and Marston, S. (2022). Human geography: Places and regions in global context (8th Edition). Pearson Education.

3. Rubenstein, J. (2020). The cultural Landscape: An introduction to human geography (13th Edition). Pearson Education

### Experimental Economics

1.  Friedman, D. (1994) Experimental methods: A primer for economists. Cambridge University Press.

2.  Gibbons, R. (1992) Game theory for applied economists. Princeton University Press.

### Spatial Economics

1.  Lovelace, R., Nowosad, J., and Muenchow, J. (2019). [Geocomputation with R](https://r.geocompx.org/index.html). CRC Press.

2.  Comber, L., and Brunsdon, C. (2020). Geographical data science and spatial data analysis: An Introduction in R. Sage.

3.  Kopczewska, K. (2020). Applied spatial statistics and econometrics: Data analysis in R. Routledge.

### Data Science

1. McKinney, W. (2022). [Python for data analysis: Data wrangling with pandas. numpy, and jupyter](https://wesmckinney.com/book/).

2.  Wickham, H., Çetinkaya-Rundel, M., and Grolemund, G. (2023). [R for data science (2e)](https://r4ds.hadley.nz/). O'Reilly.

3.  Llaudet, E., and Imai, K. (2022). Data analysis for social science: A friendly and practical introduction. Princeton University Press.

4.  Imai, K. (2017) Quantitative social science: An introduction. Princeton University Press.

5.  Wickham, H., Navarro, D., and Pedersen, T. (2023) [ggplot2: Elegant graphics for data analysis (3e)](https://ggplot2-book.org/).

6.  Heiss, F. (2016). [Using R for introductory econometrics](http://www.urfie.net/?fbclid=IwAR0Iax1Am67ZTTUmaCf_zE7ObMVrcAZ-2hEsuJMErMCyi3qvlQ4WC9wttbI). Düsseldorf, Germany: Florian Heiss.

### Energy Economics

1. Schwarz, P. (2021). Energy Economics. Routledge.

2. Zweifel, P., Praktiknjo, A., and Erdmann, G. (2017). Energy Economics: Theory and Applications. Springer.

3. Bhattacharyya, S. (2011). Energy Economics: Concepts, Issues, Markets, and Governance. Springer.

Updated on: `r Sys.Date()`
