---
title: "CV"
author: Moinul Islam
date: "`r Sys.Date()`"
output:
   pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
# uncomment this line to produce HTML and PDF in RStudio:
knit: pagedown::chrome_print
---

```{css, echo=FALSE}
.pagedjs_page:not(:first-of-type) {
  --sidebar-width: 0rem;
  --sidebar-background-color: #ffffff;
  --main-width: calc(var(--content-width) - var(--sidebar-width));
  --decorator-horizontal-margin: 0.2in;
}
```

# Aside

## Contact Info {#contact}

-   <i class="fa fa-envelope"></i> [moinul.eco\@gmail.com](mailto:lijia.yu@outlook.com){.email}
-   <i class="fa fa-globe"></i> <https://moineco.github.io/moinul/research.html>
-   <i class="fa fa-github"></i> <https://github.com/moineco>
-   <i class="fa fa-twitter"></i> moinul_econ
-   <i class="fab fa-linkedin"></i> <https://www.linkedin.com/in/moinul-islam-b7a140263/>

## Skills {#skills}

Conduct issue oriented empirical research

Explore research that integrates environmental science, environmental economics, ecological economics, and public policy.

Experienced in econometric analysis, statistical analysis and spatial analysis

## Programs

Use regularly: R, Python, STATA,  ArcGIS, LaTeX, GNU Emacs  

Use periodically: QGIS, EViews, oTree


# Main

## Moinul Islam {#title}

### I am working as an Associate Professor at Kochi University of Technology. My affiliations are listed below:

**a.** School of Economics and Management, Kochi University of Technology, 2-22 Eikokuji, Kochi City, Kochi 780-8518, Japan

**b.** Research Institute for Future Design, Kochi University of Technology, 2-22 Eikokuji, Kochi City, Kochi 780-8515, Japan

I have received my Doctor of Engineering (D.Eng.) degree from Kyushu University in 2016. My research focuses are:

1.  Applied Economics
2.  Environmental Economics
3.  International Economics
4.  Agricultural Economics
5.  Field Experiments
6.  Public Policy

I am experienced in econometric analysis, statistical analysis and spatial analysis. I have extensive skills to conduct quantitative research and social experiments to assess the public policy.

## Education {data-icon="graduation-cap" data-concise="true"}

### Kyushu University

Doctor of Engineering (D.Eng.) 

Kyushu, Japan

2016

### International University of Japan

M.A in International Development (Economics)

Niigata, Japan

2012

### Shahjala University of Science & Technology

M.S.S in Economics

Sylhet, Bangladesh

2007

### Shahjala University of Science & Technology

B.S.S in Economics

Sylhet, Bangladesh

2006

## Professional Experience {data-icon="laptop"}

### Associate Professor

Kochi University of Technology

Kochi, Japan

Current - 2024

-   Work as a vice director of Research Institute for Future Design (RIFD)
-   Acquire external research funds to initiate field experiments in various developing countries
-   Supervise Ph.D. students
-   Lead and design experiments in field and laboratory

### Assistant Professor

Kochi University of Technology

Kochi, Japan

2024 - 2020

-   Conduct environmental economics and experimental economics research
-   Establish the *Human Geography and Economics* laboratory

### Assistant Professor

Hiroshima University

Hiroshima, Japan

2020 - 2019

-   Work as an assistant professor at IDEC, Hiroshima University
-   Teach research methodology to international graduate students

### Assistant Professor

Kyushu University

Kyushu, Japan

2019 - 2016

-   Perform environmental economics research towards understanding inclusive wealth and sustainable development
-   Collaborate with leading researchers in the field of environmental economics and environmental science

### Researcher

Tohoku University

Sendai, Japan

2012

-   Work as a research associate at Graduate School of Environmental Studies
-   Analyze environmental and energy data

## Teaching Experience {data-icon="chalkboard-teacher"}

### Future Design

Instructor of "future design" at Kochi University of Technology

Kochi, Japan

Current - 2023

### International Economics

Instructor of "International Economics" at Kochi University of Technology

Kochi, Japan

Current - 2022

### Human Geography

Instructor of "Human Geography" at Kochi University of Technology

Kochi, Japan

Current - 2025

### Geoeconomics

Instructor of "geoeconomics" at Kochi University of Technology

Kochi, Japan

2024 - 2021

### Research Methodology

Instructor of "research methodology" at Hiroshima University

Hiroshima, Japan

2020 - 2019

## Journal articles (peer-review) {data-icon="file"}

### Rahman, M., Asma, K., Islam, M., Saijo, T., and Kotani, K. (2025). Does future design induce people to make a persistent change to sustainable food consumption?

*Food Policy* (forthcoming). [Q1]

Bangladesh

2025

### Tawhidul, I., Asma, K., Islam, M., and Kotani, K. (2025). Arsenic health risks and interaction with salinity in coastal areas of Bangladesh.

*Frontiers in Public Health* (forthcoming). [Q1]

Bangladesh

2025

### Rahman, M., Asma, K., Islam, M., and Kotani, K. (2025). Drivers for sustainable food purchase intentions: Prosocial attitudes for future generations and environmental concerns.

*Future Foods*, 11, 100609. [Q1] (<https://doi.org/10.1016/j.fufo.2025.100609>)

Bangladesh

2025

### Sharofiddinov, H., [Islam, M.]{.underline}, Kotani, K. (2025). Adaptation indicator to climate change and farm sizes in agriculture: A reflection of farming culture and history.

*Ecological Indicators*, 170, 112976. [Q1] (<https://doi.org/10.1016/j.ecolind.2024.112976>)

Tajikistan

2025

### Managi, S., [Islam, M.*,]{.underline} , Zhang, D., and Flammer, C. (2024). Nature positive strategy with social and economic policy.

*Sustainability Science*, 1–3. [Q1] (<https://doi.org/10.1007/s11625-024-01606-2>)

Global

2024

### [Islam, M.,]{.underline} Kotani, K., & Managi, S. (2024). Nature dependence and seasonality change perceptions for climate adaptation and mitigation.

*Economic Analysis and Policy*, 81, 34-44. [Q1] (<https://doi.org/10.1016/j.eap.2023.11.001>)

Bangladesh

2024

### Husniddin, S., [Islam, M.,]{.underline} & Kotani, K. (2024). How does the number of water users in a land reform matter for water availability in agriculture?

*Agricultural Water Management*, 293, 108677. [Q1] (<https://doi.org/10.1016/j.agwat.2024.108677>)

Tajikistan

2024

### Managi, S., [Islam, M.*,]{.underline} Zhang, D., Zaied, Y., & Saito, O. (2023). Natural capital accounting for sustainable cities.

*Sustainability Science*, 18, 2049--2051. [Q1] (<https://doi.org/10.1007/s11625-023-01356-7>)

Global

2023

### Yamaguchi, R., [Islam, M.,]{.underline} and Managi, S. (2023). Natural capital and wealth accounting for sustainability assessment: A global perspective

*Review of Env. and Resource Econ.*, 16, 431-465. [Q2] (<http://dx.doi.org/10.1561/101.00000148>)

Global

2023

### [Islam, M.]{.underline}, Zhang, B., and Managi, S. (2022). The tradeoff between natural capital and other capitals in Pakistan

*Sustainability Science*, 17, 1799-1811. [Q1] (<https://doi.org/10.1007/s11625-022-01143-w>)

Pakistan

2022

### Managi, S., [Islam, M.*,]{.underline} Saito, O. et al. (2022). Valuation of nature and nature's contributions to people

*Sustainability Science*, 17, 701-705. [Q1] (<https://doi.org/10.1007/s11625-022-01140-z>)

Global

2022

### [Islam, M.]{.underline}, and Managi, S. (2022). Valuation of nature's contribution in Ladakh, India: An inclusive wealth method

*Sustainability Science*, 17, 905-918. [Q1] (<https://doi.org/10.1007/s11625-021-01030-w>)

India

2022

### N'dri, L., [Islam, M.*]{.underline}, and Kakinaka, M. (2021). ICT and environmental sustainability: Any differences in developing countries?

*Journal of Cleaner Production*, 297, 126642. [Q1] (<https://doi.org/10.1016/j.jclepro.2021.126642>)

Developing

2021

### Badamvaanchig, M., [Islam, M.*]{.underline}, and Kakinaka, M. (2021). Pass-through of commodity price to Mongolian stock price: Symmetric or asymmetric?

*Resources Policy*, 70, 101955. [Q1] (<https://doi.org/10.1016/j.resourpol.2020.101955>)

Mongolia

2021

### Hongsakhone, S., [Islam, M.*]{.underline}, and Ichihashi, M. (2021). Producing a village input-output table (VIOT) from household survey data: A case study of a VIOT for a rural village in northern Lao PDR

*Journal of Economic Structures*, 10, 1-24. (<https://doi.org/10.1186/s40008-020-00231-3>)

Lao PDR

2021

### Sharifi, A., Simangan, D., Lee, C., Reyes, S., Katramiz, T., Josol, J., & [Islam, M.]{.underline} (2021). Climate-induced stressors to peace: A review of recent literature

*Environmental Research Letters*, 16, 073006. [Q1] (<https://doi.org/10.1088/1748-9326/abfc08>)

Global

2021

### Simangan, D., Virji, H., Hendrix, C., [Islam, M.]{.underline}, Kaneko, S., Ma, Y., Mechler, R., Pangotra, P., Peters, K., Sharifi, A. and Shams, S. (2021). A co-designed heuristic guide for investigating the peace-sustainability nexus in the context of global change

*Sustainability Science*, 16, 1097-1109. [Q1] (<https://doi.org/10.1007/s11625-021-00970-7>)

Global

2021

### Essandoh, O. K., [Islam, M.*]{.underline}, and Kakinaka, M. (2020). Linking international trade and foreign direct investment to $CO_2$ emissions: Any differences between developed and developing countries?

*Science of The Total Env.*, 712, 136437. [Q1] (<https://doi.org/10.1016/j.scitotenv.2019.136437>)

Developing

2020

### Jingyu, W., Yuping B., Yihzong W., Zhihui L., Xiangzheng D., [Islam M.]{.underline}, and Managi S. (2020). Measuring inclusive wealth of China: Advances in sustainable use of resources

*Journal of Environmental Management*, 264, 110328. [Q1] (<https://doi.org/10.1016/j.jenvman.2020.110328>)

China

2020

### Hotak, S., [Islam, M.*]{.underline}, Kakinaka, M. and Kotani, K. (2020). Carbon emissions and carbon trade balances: International evidence from panel ARDL analysis

*Env. Science and Pollution Res.*, 27, 24115-24128. [Q1] (<https://doi.org/10.1007/s11356-020-08478-w>)

Global

2020

### Coulibaly, T., [**Islam, M.**]{.underline}, and Managi, S. (2020). The Impacts of climate change and natural disasters on agriculture in African countries

*Economics of Disasters and Climate Change*, 4, 347-363. (<https://doi.org/10.1007/s41885-019-00057-9>)

Africa

2020

### Coulibaly, T., Wakamatsu, M., [Islam, M.]{.underline}, Fukai, H., Managi, S. and Zhang, B. (2020). Differences in water policy efficacy across South African water management areas

*Ecological Economics*, 175, 106707. [Q1] (<https://doi.org/10.1016/j.ecolecon.2020.106707>)

South Africa

2020

### [Islam, M.]{.underline}, and Managi, S. (2019). Green growth and pro-environmental behavior: Sustainable resource management using natural capital accounting in India

*Resources Conservation and Recycl.*, 145, 126-138. [Q1] (<https://doi.org/10.1016/j.resconrec.2019.02.027>)

India

2019

### Managi, S., [Islam, M.]{.underline}, Saito, O., Stenseke, M., Dziba, L., Lavorel, S., Pascual, U., and Hashimoto, S. (2019). Valuation of nature and nature's contributions to people

*Sustainability Science*, 1463-1465. [Q1] (<https://doi.org/10.1007/s11625-019-00732-6>)

Global

2019

### [Islam, M.]{.underline}, Kanemoto, K., and Managi, S. (2019). Growth potential for $CO_2$ emissions transfer by tariff reduction

*Env. Research Let.*, 14, 024011. [Q1] (<https://iopscience.iop.org/article/10.1088/1748-9326/aaf688/meta>)

Global

2019

### Yamaguchi, R., [Islam, M.]{.underline}, and Managi, S. (2019). Inclusive wealth in the 21st century

*Letters in Spatial and Resource Sciences*, 12, 101-111. [Q2] (<https://doi.org/10.1007/s12076-019-00229-x>)

Global

2019

### Ying Lee, C., Lotsu, S., [Islam, M.*]{.underline}, Yoshida, Y., and Kaneko, S. (2019). The Impact of an energy efficiency improvement policy on the economic performance of electricity-intensive firms in Ghana

*Energies*, 12, 3684. [Q3] (<https://doi.org/10.3390/en12193684>)

Ghana

2019

### [Islam, M.]{.underline}, Yamaguchi, R., Sugiawan, Y., and Managi, S. (2018). Valuing natural capital and ecosystem services: A literature review

*Sustainability Science*, 14, 159-174. [Q1] (<https://doi.org/10.1007/s11625-018-0597-7>)

Global

2018

### [Islam, M.]{.underline}, and Managi, S. (2018). Sustainable adaptation to multiple water risks in agriculture: Evidence from Bangladesh

*Sustainability* (Switzerland), 10(6). [Q2] (<https://doi.org/10.3390/su10061734>)

Bangladesh

2018

### Rajapaksa, D., [Islam, M.]{.underline}, and Managi, S. (2018). Pro-environmental behavior: The role of public perception in infrastructure and the social factors for sustainable development

*Sustainability* (Switzerland), 10, 937. [Q2] (<https://doi.org/10.3390/su10040937>)

Global

2018

### Tolliver, C., [Islam, M.]{.underline}, Shin, K., and Managi, S. (2018). The impact of energy security risks on energy consumption

*Int. Journal of Innovation and Sust. Dev.*, 12, 258--270. [Q4] (<https://doi.org/10.1504/IJISD.2018.091522>)

Global

2018

### Sugiawan, Y., [Islam, M.]{.underline}, and Managi, S. (2017). Global marine fisheries with environmental sustainability

*Economic Analysis and Policy*, 55, 158-168. [Q1] (<https://doi.org/10.1016/j.eap.2017.08.004>)

Global

2017

### Rajapaksa, D., [Islam, M.]{.underline}, and Managi, S. (2017). Natural capital depletion: The impact of natural disasters on inclusive growth

*Economics of Disasters and Climate Change*, 1, 233--244. (<https://doi.org/10.1007/s41885-017-0009-y>)

Global

2017

### [Islam, M.]{.underline}, Kanemoto, K., and Managi, S. (2016). Impact of trade openness and sector trade on embodied greenhouse gases emissions and air pollutants

*Journal of Industrial Ecology*, 20, 494-505. [Q1] (<https://doi.org/10.1111/jiec.12455>)

Global

2016

### [Islam, M.]{.underline}, Kotani, K., and Managi, S. (2016). Climate perception and flood mitigation cooperation: A Bangladesh case study

*Economic Analysis and Policy*, 49, 117-133. [Q1] (<https://doi.org/10.1016/j.eap.2016.01.001>)

Bangladesh

2016

### [Islam, M.]{.underline}, and Kotani, K. (2016). Changing seasonality in Bangladesh

*Regional Environmental Change*, 16, 585-590. [Q2] (<https://doi.org/10.1007/s10113-015-0758-5>)

Bangladesh

2016

## International policy reports (peer-review) {data-icon="laptop"}

### Inclusive wealth report 2023

United Nation Environmental Program (UNEP)

Global

2023

### Inclusive wealth of Pakistan: The case for investing in natural capital and restoration

United Nation Environmental Program (UNEP)

Pakistan

2022

### Future design: For the survival of humankind

Think7: Research-based policy recommendations for the G7

Global

2022

## Book chapters (peer-review) {data-icon="book"}

### [**Islam, M.**]{.underline}, and Managi, S. (2021). Global human capital: View from inclusive wealth

In measuring human capital (pp. 39-54). Academic Press. ISBN: 9780128190579.

Global

2021

### Sugiawan, Y., [**Islam, M.**]{.underline}, and Managi, S. (2019). Global marine fisheries with environmental sustainability

In wealth, inclusive growth and sustainability. Routledge, New York, USA.

Global

2019

### Sankaralingam, I., [**Islam, M.**]{.underline}, Nozawa, W., and Managi, S. (2019). Impact of infrastructure in India. In Wealth, Inclusive Growth and Sustainability

In wealth, inclusive growth and sustainability. Routledge, New York, USA.

India

2019

### Jumbri, I., [**Islam, M.**]{.underline}, and Managi, S. (2019). Inclusive wealth adjusted by total factor productivity as a sustainable measurement: global productivity analysis

In wealth, inclusive growth and sustainability. Routledge, New York, USA.

Global

2019

### Coulibaly, T., [**Islam, M.**]{.underline}, and Managi, S. (2019). The impact of climate change and extreme events on agriculture in Africa

In wealth, inclusive growth and sustainability. Routledge, New York, USA.

Africa

2019

### Qiuyi, C., [**Islam, M.**]{.underline}, and Managi, S. (2019). Human capital change and social impact under China's universal two-child policy

In wealth, inclusive growth and sustainability. Routledge, New York, USA.

China

2019

### Mahful, R., [**Islam, M.**]{.underline}, Nakayam, H., and Managi, S. (2019). The effect of landfill gas emission on global warming and workers' health in Indonesia

In wealth, inclusive growth and sustainability. Routledge, New York, USA.

Indonesia

2019

## International conferences and symposiums {data-icon="folder"}

### Can future design persistently improve indoor air quality? 

The 8th International Symposium on Frontier Technology (Kochi University of Technology),

Kochi, Japan

2024

### Future design (FD) social experiments 

17th association of behavioral economics and finance conference (Kochi University of Technology)

Kochi, Japan

2023

### Relationship of trade openness and renewable energy with inorganic nitrogen intensity in ecosystem

SEEPS workshop 2023 (Kyushu University)

Kyushu, Japan

2023

### Future design workshop on inequality

4th International conference on anticipation (Arizona State University)

Arizona, USA

2022

### Nitrogen cycle and intergenerational sustainability

Future design 2022

Kochi, Japan

2022

### Inclusive wealth of nations

Q-AOS symposium on inclusive growth (Kyushu University)

Kyushu, Japan

2021

### Growth potential for $CO_2$ emissions transfer by United States−China trade battle

SEEPS 2019 annual conference (Fukushima University)

Fukushima, Japan

2019

### Natural capital of nations for sustainable development

IPSA world congress of political science

Brisbane, Australia

2018

### Inclusive wealth accounting

Joint Tianjin University-Kyushu University workshop on economics (Tianjin University)

Tianjin, China

2018

### Natural capital of nations

Workshop on sustainability, SDGs and security (Kyushu University)

Kyushu, Japan

2018

### Farmer's adaptation strategy in Bangladesh

SEEPS (Kobe University)

Kobe, Japan

2013

## Research grants {data-icon="laptop"}

### Grants-in-Aid for Scientific Research from the Japanese government. Category: Grant-in-Aid for Scientific Research (C). Principal investigator: [**Moinul Islam**]{.underline}. Grant number: 25K05109.

JSPS

Japan

2025 - 2028

### Grants-in-Aid for Scientific Research from the Japanese government. Category: Grant-in-Aid for Early-Career Scientists. Principal investigator: [**Moinul Islam**]{.underline}. Grant number: 21K13290.

JSPS

Japan

2025 - 2021

### Grants-in-Aid for Scientific Research from the Japanese government. Category: Fund for the Promotion of Joint International Research. Principal Investigator: Koji Kotani. Grant number: 22KK0020.

JSPS

Japan

2027 - 2022

### Grants-in-Aid for Scientific Research from the Japanese government. Category: Grant-in-Aid for Research Activity Start-up. Principal investigator: [**Moinul Islam**]{.underline}. Grant number: 19K24384.

JSPS

Japan

2021 - 2019

## Working papers {data-icon="file"}

### Rahman, M., Asma, K., [**Islam, M.**]{.underline}, Saijo, T., and Kotani, K. Does future design induce people to make a persistent change to sustainable food consumption?

Working Papers SDES-2024-4, Kochi University of Technology, School of Economics and Management

Bangladesh

2024

### Husniddin, S., [**Islam, M.**]{.underline}, and Kotani, K. Farm sizes and adaptation responses to climate change in agriculture: A reflection of Tajikistan’s farming culture and history. 

Working Papers SDES-2024-2, Kochi University of Technology, School of Economics and Management

Tajikistan

2024

### Husniddin, S., [**Islam, M.**]{.underline}, and Kotani, K. How does the number of water users in a land reform matter for irrigation water availability?

Working Papers SDES-2023-5, Kochi University of Technology, School of Economics and Management

Tajikistan

2023

### Husniddin, S., [**Islam, M.**]{.underline}, and Kotani, K. Does the reorganization of large agricultural farms decrease irrigation water availability? A case study of Tajikistan

Working Papers SDES-2022-3, Kochi University of Technology, School of Economics and Management

Tajikistan

2022

### [**Islam, M.**]{.underline}, and Kotani, K. Who perceive seasonality change? A case of the Meghna basin, Bangladesh

Working Papers SDES-2020-15, Kochi University of Technology, School of Economics and Management

Bangladesh

2020

### [**Islam, M.**]{.underline}, and Kotani, K. Six or four seasons? An evidence for seasonal change in Bangladesh

Working Papers SDES-2014-11, Kochi University of Technology, School of Economics and Management,

Bangladesh

2014

### [**Islam, M.**]{.underline}, and Kotani, K. Six or four seasons? Perceptions of climatic changes and people's cooperative attitudes toward food protection in Bangladesh

Working Paper EMS-2013-06, International University of Japan, Economics & Management Series

Bangladesh

2013

## Project Experience {data-icon="suitcase"}

### United Nations Environmental Program (UNEP)

Inclusive Wealth Project

Kyushu, Japan

Current - 2016

::: concise
-   Collect data to measure the "Inclusive Wealth of Nations"
-   Analyze data and create "Inclusive Wealth Index"
-   Publish the "Inclusive Wealth Report" report as a contributing author
:::

### Research Institute of Economy, Trade and Industry (RIETI)

Economic analysis and policy

Kyushu, Japan

2016 - 2013

::: concise
-   Collect and analyze the trade and emission data of Japan
-   Prepare the report based on the empirical findings
:::

### Strategic Energy and Resource Management and Sustainable Solutions (SERMS)

Environmental economics and policy

Sendai, Japan

2012

::: concise
-   Analyze the natural disaster data of the Great East Japan Earthquake
-   Prepare the report based on the empirical findings
:::

## Peer reviewer 

### Economic Analysis and Policy

12 papers

Elsevier

2025 - 2016

### Journal of Cleaner Production

3 paper

Elsevier

2022

### Environmental Research Letters

2 paper

IOPScience

2018

### Journal of Industrial Ecology

1 paper

Wiley

2025

### Environmental Science and Pollution Research

3 paper

Springer

2021

### Global Sustainability

2 paper

Cambridge University Press

2020

### Sustainability Science

5 papers

Springer

2025 - 2016

### Journal of Behavioral and Experimental Economics

2 paper

Springer

2023

## Scholarly Memberships

### AERE

Association of Environmental and Resource Economists

United States

Current

### SEEPS

Society for Environmental Economics and Policy Studies

Japan

Current






