---
title: "Emacs"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Updated on: `r Sys.Date()`

# GNU Emacs

GNU Emacs isn't a text editor only, it's the ultimate productivity environment. Emacs can be installed on GNU/Linux, macOS and Windows. The latest stable version is 29.2, so it's best to try and find that version for your operating system. Installing Emacs by GUI is straightforward. However, to get a full grip on your installation, using the *terminal* is recommended. I will explain the ways to installing Emacs by using *terminal*.

## LinuxOS

#### Fedora

- After updating the package list in the Fedora Linux system, enter the following command to install the Emacs editor through the **DNF** package manager:

```{txt}
$ sudo dnf install emacs
```

#### Ubuntu

- After updating the package list in the Ubuntu Linux system, enter the following command to install the Emacs editor through the **APT** package manager:

```{txt}
$ sudo apt install emacs
```

- If you are using Ubuntu desktop version and want to get the graphical Emacs editor, you can use this command:

```{txt}
$ sudo apt install emacs-gtk
```

- By executing the previous commands, the graphical version of Emacs, along with its dependencies, will be downloaded and installed.

- After you have installed Emacs, run the following command to ensure a successful installation of the Emacs text editor:

```{txt}
$ emacs --version
```

## MacOS

#### Homebrew

- Installation on `MacOS` with `Homebrew` is easy! 
- Install `Homebrew` by following the instructions in <https://brew.sh/>
- There's a default recipe called `Emacs` which can be installed with the following command:

```{txt}
% brew install --cask emacs
```

#### MacPorts

- Installation on `MacOS` with `MacPorts` is useful!
- Install `MacPorts` by following the instructions in <https://www.macports.org/install.php>
- The installation command of Emacs by using `MacPorts` is as below:

```{txt}
% sudo port install emacs-app
```

#### MacPorts under Proxy

This tutorial is to let `Macports` to work over proxy. Download the latest installation package  for your particular OS from: `http://www.macports.org/install.php`.  Follow through the prompts after opening it and install `Macports` but then trying to `selfupdate` might give error. This is because the shell environment doesn’t have the variables specifying your systems proxy settings.

1. Use the following code to edit sources.conf using the vi editor in bash:

```{txt}
sudo vim /opt/local/etc/macports/sources.conf
```

2. Once the file is opened in the vi editor press the `a` key on your keyboard to enter into –insert– mode. Scroll down to the bottom of file and comment out the following line by typing `#` in front of it.

```{txt}
rsync://rsync.macports.org/release/tarballs/ports.tar [default]
```

3. Bellow that line insert this line which will tell Macports to go fetch the daily tarball over http

```{txt}
http://www.macports.org/files/ports.tar.gz [default]
```

4. Next, press the `esc` key on your keyboard to exit –insert– mode. Then type `:x` and press `return` to save your changes and return to terminal.

5. Similar to editing the sources.conf by using the vi editor in bash, edit the sudoer file:

```{txt}
sudo visudo
```

6. Scroll to the bottom, enter into –insert– mode and append the following to the list of default specifications

```{txt}
Defaults        env_keep += "http_proxy HTTP_PROXY ftp_Proxy FTP_PROXY rsync_proxy RSYNC_PROXY"
```

Next, escape out of the –insert– mode and save your changes.

7. Now, type the following at the terminal to export environment variables [Following proxy information is for Kochi University of Technology. For your institution, please find the appropriate proxy settings from administrator]. Replace “username”, “password”, “proxyURL” and “portNumber” with their values specifying your proxy settings:

```{txt}
export http_proxy=http://proxy.noc.kochi-tech.ac.jp:3128
export HTTP_PROXY=http://proxy.noc.kochi-tech.ac.jp:3128
export ftp_proxy=ftp://proxy.noc.kochi-tech.ac.jp:3128
export FTP_PROXY=ftp://proxy.noc.kochi-tech.ac.jp:3128
export rsync_proxy=proxy.noc.kochi-tech.ac.jp:3128
export RSYNC_PROXY=proxy.noc.kochi-tech.ac.jp:3128
```

8. Use the bellow command to check the environment variables being used in the current session of the bash shell

```{txt}
env
```

Remember to check for these environment variables every time you run your Terminal and are about to use things like port, curl, homebrew, etc. that make use of your internet connection.

9. In case you want to erase those environment variables you can use:

```{txt}
unset http_proxy HTTP_PROXY
```

10. Sync the port tree over http. Use the bellow command, not “sudo port selfupdate”

```{txt}
sudo port -d sync
```

11. Move onto `sudo port -v self update`

Without closing the terminal, you can do self update under a proxy. If you close the terminal, you just need to run the following code first and `sudo port -v self update` next:

```{txt}
export http_proxy=http://proxy.noc.kochi-tech.ac.jp:3128
export HTTP_PROXY=http://proxy.noc.kochi-tech.ac.jp:3128
export ftp_proxy=ftp://proxy.noc.kochi-tech.ac.jp:3128
export FTP_PROXY=ftp://proxy.noc.kochi-tech.ac.jp:3128
export rsync_proxy=proxy.noc.kochi-tech.ac.jp:3128
export RSYNC_PROXY=proxy.noc.kochi-tech.ac.jp:3128
```

## Windows

- Installation on `Windows` with `MSYS2` is convenient!
- Install `MSYS2` by following the instructions in <https://www.msys2.org/>
- If you use `MSYS2`, you can install it using `Pacman`:

```{txt}
pacman -S mingw-w64-x86_64-emacs
```

# Org-roam
Homepage (<https://www.orgroam.com/>)

- Org Roam is an extension to Org Mode. Install the org-roam package from MELPA using package.el, straight.el or any other package manager you normally use to install packages.

- Inside your Emacs working environment, need to customize **.emacs** file to become able to utilize the necessary packages.

- If you use use-package with package.el, add this to your configuration temporarily and execute it to install org-roam: 

```{txt}
(use-package org-roam
  :ensure t)
```

- After ***Org Roam** has been installed, the most important thing to configure is the folder where your Org Roam files will be located.

- By default, this will be a folder called org-roam in your **HOME** directory but you will probably want to set this to something else. No matter what path you use, things will be slightly easier if you create the folder in advance! 

- We’ll also add some necessary key bindings and a call to org-roam-setup to make sure everything is ready to go. 

```{txt}
(use-package org-roam
  :ensure t
  :custom
  (org-roam-directory "/Users/username/Documents/Dropbox/roam_notes")
  :bind (("C-c n l" . org-roam-buffer-toggle)
         ("C-c n f" . org-roam-node-find)
         ("C-c n i" . org-roam-node-insert))
  :config
  (org-roam-setup))
```

- If you've never used Org Roam before, you can set the variable org-roam-v2-ack to t in your configuration. Here's how to set the variable in your configuration:

```{txt}
(use-package org-roam
  :ensure t
  :init
  (setq org-roam-v2-ack t)
  :custom
  (org-roam-directory "/Users/username/Documents/Dropbox/roam_notes")
  :bind (("C-c n l" . org-roam-buffer-toggle)
         ("C-c n f" . org-roam-node-find)
         ("C-c n i" . org-roam-node-insert))
  :config
  (org-roam-setup))
```

- Creating your first node. Let's create our first node! We can use the *C-c n f* binding to invoke org-roam-node-find which brings up a completion session to select or create a node.

- Since we want to create a new node, we can type in the desired node name “Econometrics” and press **Enter**.

- For now, we can add some text to the file and then press *C-c C-c* to confirm the capture to save the file. 

- Let's follow the same process to create another node called “Logit_model”. 

- The real power of Org Roam begins when you start linking your node files together! 

- Here's an updated configuration that makes node completions easier: 

```{txt}
(use-package org-roam
  :ensure t
  :init
  (setq org-roam-v2-ack t)
  :custom
  (org-roam-directory "/Users/username/Documents/Dropbox/roam_notes")
  (org-roam-completion-everywhere t)
  :bind (("C-c n l" . org-roam-buffer-toggle)
         ("C-c n f" . org-roam-node-find)
         ("C-c n i" . org-roam-node-insert)
         :map org-mode-map
         ("C-M-i"    . completion-at-point))
  :config
  (org-roam-setup))
```

