---
title: "Biography"
output:
  html_document:
    theme: darkly
    css: darkly_custom.css
    toc: true
    toc_float: true
    collapsed: false
    number_sections: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

### Background

I am Dr. Moinul Islam, serving as an Associate Professor at Kochi University of Technology, Japan. I earned my Doctor of Engineering (D.Eng.) [equivalent to Ph.D. in Environmental Engineering] degree from Kyushu University in 2016. My expertise spans applied economics, data science, international economics, sustainability science with a particular interest in field experiments. My research focuses on applying economic models and data science to address critical public policy challenges. I am engaged in understanding the far-reaching impacts of human behavior on sustainable development and finding solutions through experimental evidence-based public policies. 

I have extensive experience in designing and implementing laboratory, field, and survey experiments, as well as in collecting and analyzing primary data to address rigorous research questions. I am highly proficient in working with secondary data—including cross-sectional, time series, spatial, and panel datasets—using advanced econometric methods to generate robust and policy-relevant insights. My analytical toolkit includes R, Python, Stata, and ArcGIS, which I employ to conduct reproducible, data-driven research integrating causal inference and modern quantitative techniques. My vision is to design a future where our daily behavior fosters human–nature coexistence. 

### Research interests

Applied Economics, Agricultural Economics, Data Science, Environmental Economics, Field Experiments, International Economics

### Affiliations

Associate Professor, School of Economics and Management, Kochi University of Technology, 2-22 Eikokuji, Kochi City, Kochi 780-8518, Japan

Associate Professor, Research Institute for Future Design, Kochi University of Technology, 2-22 Eikokuji, Kochi City, Kochi 780-8515, Japan

Research Fellow, Urban Institute, Kyushu University, 744 Motooka, Nishi-ku, Fukuoka 819-0395, Japan

### Work experiences

**2024-current**, Associate Professor, School of Economics and Management & Research Institute for Future Design, Kochi University of Technology, Kochi, Japan

**2020-2024**, Assistant Professor, School of Economics and Management & Research Institute for Future Design, Kochi University of Technology, Kochi, Japan

**2019-2020**, Assistant Professor, Graduate School for International Development and Cooperation (IDEC), Hiroshima University, Hiroshima, Japan

**2016-2019**, Assistant Professor, Graduate School of Urban and Environmental Engineering, Kyushu University, Fukuoka, Japan

**2012-2015**, Research Assistant, Graduate School of Environmental Studies, Tohoku University, Sendai, Japan

### Academic qualifications

**2016**, Doctor of Engineering (D.Eng.) [equivalent to Ph.D. in Environmental Engineering], Kyushu University, Kyushu, Japan

**2012**, Master of Arts (M.A.) in International Development, International University of Japan, Niigata, Japan

**2007**, Master of Social Science (M.S.S.) in Economics, Shahjala University of Science and Technology, Sylhet, Bangladesh

**2006**, Bachelor of Social Science (B.S.S.) in Economics, Shahjala University of Science and Technology, Sylhet, Bangladesh

### Research grants as PI

I receive the Japanese Government **Grants-in-Aid for Scientific Research (C)** [2025-2028] for my research on sustainable water management. This funding will support my efforts to enhance water sustainability in the face of environmental and economic challenges. I also received the **Grant-in-Aid for Early-Career Scientists** [2021-2025] and the **Grant-in-Aid for Research Activity Start-up** [2019-2022] from Japan Society for the Promotion of Science (JSPS), which have supported my applied economics research for over a decade.

::: {#tbl-panel layout-ncol="2"}
|                   |                                                   |
|-------------------|---------------------------------------------------|
| Primary fund type | **Grant-in-Aid for Scientific Research (C)**      |
| Funder            | Japan Society for the Promotion of Science (JSPS) |
| Grant number      | 25K05109                                          |
| Keywords          | Sustainable water management; social experiment   |

: KAKENHI Kiban C

|                   |                                                   |
|-------------------|---------------------------------------------------|
| Primary fund type | **Grant-in-Aid for Early-Career Scientists**      |
| Funder            | Japan Society for the Promotion of Science (JSPS) |
| Grant number      | 21K13290                                          |
| Keywords          | Public health; social experiment                  |

: KAKENHI Wakate

|                   |                                                   |
|-------------------|---------------------------------------------------|
| Primary fund type | **Grant-in-Aid for Research Activity Start-up**   |
| Funder            | Japan Society for the Promotion of Science (JSPS) |
| Grant number      | 19K24384                                          |
| Keywords          | Environmental economics; economic policy          |

: KAKENHI Start-up
:::

### Programming and Software

- Programming language: R, Python, Lisp

- Software to use regularly: ArcGIS, Quarto, STATA, LaTex, GNU Emacs

- Software to use occasionally: QGIS, EViews, oTree, Microsoft Office

### Languages

Bengali (Native), English (Business), Japanese (Business)

### Links of my profile

|  |  |
|----|----|
| [Web of Science](https://www.webofscience.com/wos/author/record/M-9369-2019) | [Scopus](https://www.scopus.com/authid/detail.uri?authorId=55348122400) |
| [Kochi University of Technology](https://www.kochi-tech.ac.jp/profile/ja/islam-moinul.html) | [Research Map](https://researchmap.jp/moinul/?lang=english) |
| [Google Scholar](https://scholar.google.co.jp/citations?user=UTZTmJ0AAAAJ&hl=en) | [Orcid](https://orcid.org/0000-0002-0309-3156) |

<!-- ### My mission -->

<!-- -   Conduct empirical research to deliver evidence-based policy recommendations that guide long-term economic transformation toward sustainable human behavior and human–nature coexistence -->

<!-- ### My strategies -->

<!-- -   Analyze the gaps between current and ideal economic systems to formulate research questions at the intersection of environment, geography, and public policy, and address them through rigorous economic and experimental methods to achieve sustainable human–nature coexistence -->

<!-- ### Contact -->

<!-- moinul[dot]eco[at]gmail[dot]com -->

Updated on: `r Sys.Date()`
