---
title: "Publications"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```


# Journal Articles (peer-review) 
Updated on: `r Sys.Date()`

1. Islam, M., Zhang, B., and Managi, S. (2022). The tradeoff between natural capital and other capitals in Pakistan. Sustainability Science (forthcoming). (https://doi.org/10.1007/s11625-022-01143-w)

2. Managi, S., Islam, M., Saito, O. et al. (2022). Valuation of nature and nature’s contributions to people. Sustainability Science, 17, 701-705. (https://doi.org/10.1007/s11625-022-01140-z)

3. Islam, M., and Managi, S. (2021). Valuation of Nature’s Contribution in Ladakh, India: An Inclusive Wealth Method. Sustainability Science, 17, 905-918. (https://doi.org/10.1007/s11625-021-01030-w)

4. N’dri, L., Islam, M., and Kakinaka, M. (2021). ICT and environmental sustainability: Any differences in developing countries? Journal of Cleaner Production, 297, 126642. (https://doi.org/10.1016/j.jclepro.2021.126642)

5. Badamvaanchig, M., Islam, M., and Kakinaka, M. (2021). Pass-through of commodity price to Mongolian stock price: Symmetric or asymmetric? Resources Policy, 70, 101955. (https://doi.org/10.1016/j.resourpol.2020.101955)

6. Hongsakhone, S., Islam, M., and Ichihashi, M. (2021). Producing a village input-output table (VIOT) from household survey data: A case study of a VIOT for a rural village in northern Lao PDR. Journal of Economic Structures, 10, 1-24.  (https://doi.org/10.1186/s40008-020-00231-3)

7. Sharifi, A., Simangan, D., Lee, C. Y., Reyes, S. R. C., Katramiz, T., Josol, J. C. C., & Islam, M. (2021). Climate-induced stressors to peace: A review of recent literature. Environmental Research Letters, 16, 073006.  (https://doi.org/10.1088/1748-9326/abfc08)

8. Simangan, D., Virji, H., Hendrix, C., Islam, M., Kaneko, S., Ma, Y., Mechler, R., Pangotra, P., Peters, K., Sharifi, A. and Shams, S. (2021). A co-designed heuristic guide for investigating the peace-sustainability nexus in the context of global change. Sustainability Science, 16, 1097-1109.  (https://doi.org/10.1007/s11625-021-00970-7)

9. Essandoh, O. K., Islam, M., and Kakinaka, M. (2020). Linking international trade and foreign direct investment to CO2 emissions: Any differences between developed and developing countries? Science of The Total Environment, 712, 136437. (https://doi.org/10.1016/j.scitotenv.2019.136437)

10. Jingyu, W., Yuping B., Yihzong W., Zhihui L., Xiangzheng D., Islam M., and Managi S. (2020). Measuring inclusive wealth of China: Advances in sustainable use of resources. Journal of Environmental Management, 264, 110328.  (https://doi.org/10.1016/j.jenvman.2020.110328)

11. Hotak, S., Islam, M., Kakinaka, M. and Kotani, K. (2020). Carbon emissions and carbon trade balances: International evidence from panel ARDL analysis. Environmental Science and Pollution Research, 27, 24115-24128.  (https://doi.org/10.1007/s11356-020-08478-w)

12. Coulibaly, T., Islam, M., and Managi, S. (2020). The Impacts of climate change and natural disasters on agriculture in African countries. Economics of Disasters and Climate Change, 4, 347-363.  (https://doi.org/10.1007/s41885-019-00057-9)

13. Coulibaly, T., Wakamatsu, M., Islam, M., Fukai, H., Managi, S. and Zhang, B. (2020). Differences in water policy efficacy across South African water management areas (2020). Ecological Economics, 175, 106707.  (https://doi.org/10.1016/j.ecolecon.2020.106707)

14. Islam, M., and Managi, S. (2019). Green growth and pro-environmental behavior: Sustainable resource management using natural capital accounting in India. Resources, Conservation and Recycling, 145, 126-138.  (https://doi.org/10.1016/j.resconrec.2019.02.027)

15. Managi, S., Islam, M., Saito, O., Stenseke, M., Dziba, L., Lavorel, S., Pascual, U., and Hashimoto, S. (2019). Valuation of nature and nature’s contributions to people. Sustainability Science, 1463-1465.  (https://doi.org/10.1007/s11625-019-00732-6)

16. Islam, M., Kanemoto, K., and Managi, S. (2019). Growth potential for CO2 emissions transfer by tariff reduction. Environmental Research Letters, 14, 024011.  (https://iopscience.iop.org/article/10.1088/1748-9326/aaf688/meta)

17. Yamaguchi, R., Islam, M., and Managi, S. (2019). Inclusive wealth in the 21st century. Letters in Spatial and Resource Sciences, 12, 101-111.  (https://doi.org/10.1007/s12076-019-00229-x)

18. Ying Lee, C., Lotsu, S., Islam, M., Yoshida, Y., and Kaneko, S. (2019). The Impact of an energy efficiency improvement policy on the economic performance of electricity-intensive firms in Ghana. Energies, 12, 3684.  (https://doi.org/10.3390/en12193684)

19. Islam, M., Yamaguchi, R., Sugiawan, Y., and Managi, S. (2018). Valuing natural capital and ecosystem services: A literature review. Sustainability Science, 14, 159-174.  (https://doi.org/10.1007/s11625-018-0597-7)

20. Islam, M., and Managi, S. (2018). Sustainable adaptation to multiple water risks in agriculture: Evidence from Bangladesh. Sustainability (Switzerland), 10(6). (https://doi.org/10.3390/su10061734)

21. Rajapaksa, D., Islam, M., and Managi, S. (2018). Pro-environmental behavior: The role of public perception in infrastructure and the social factors for sustainable development. Sustainability (Switzerland), 10, 937.  (https://doi.org/10.3390/su10040937)

22. Tolliver, C., Islam, M., Shin, K., and Managi, S. (2018). The impact of energy security risks on energy consumption. International Journal of Innovation and Sustainable Development, 12, 258–270.  (https://doi.org/10.1504/IJISD.2018.091522)

23. Sugiawan, Y., Islam, M., and Managi, S. (2017). Global marine fisheries with environmental sustainability. Economic Analysis and Policy, 55, 158-168.  (https://doi.org/10.1016/j.eap.2017.08.004)

24. Rajapaksa, D., Islam, M., and Managi, S. (2017). Natural capital depletion: The impact of natural disasters on inclusive growth. Economics of Disasters and Climate Change, 1, 233–244. (https://doi.org/10.1007/s41885-017-0009-y)

25. Islam, M., Kanemoto, K., and Managi, S. (2016). Impact of trade openness and sector trade on embodied greenhouse gases emissions and air pollutants. Journal of Industrial Ecology, 20, 494-505. (https://doi.org/10.1111/jiec.12455)

26. Islam, M., Kotani, K., and Managi, S. (2016). Climate perception and flood mitigation cooperation: A Bangladesh case study. Economic Analysis and Policy, 49, 117-133.  (https://doi.org/10.1016/j.eap.2016.01.001)

27. Islam, M., and Kotani, K. (2016). Changing seasonality in Bangladesh. Regional Environmental Change, 16, 585-590. (https://doi.org/10.1007/s10113-015-0758-5)

# Reports (peer-review)
Updated on: `r Sys.Date()`

1. Inclusive Wealth of Pakistan: The Case for Investing in Natural Capital and Restoration (2021). United Nation Environmental Program (UNEP). Available from 
(https://www.unep.org/resources/report/inclusive-wealth-pakistan-case-investing-natural-capital-and-restoration)

# Book chapters
Updated on: `r Sys.Date()`

1. Islam, M., and Managi, S. (2021). Global human capital: View from inclusive wealth. In Measuring Human Capital, Academic Press, Fraumeni, Barbara M. (Ed), (forthcoming). ISBN: 9780128190579 (https://www.elsevier.com/books/measuring-human-capital/fraumeni/978-0-12-819057-9)