---
title: "Lecture"
output: 
 html_document:
    highlight: monochrome
    theme: darkly
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

## Principles of Economics

**Section 1: Microeconomics**

-   Lecture 1: Economics foundations and models

-   Lecture 2: Trade-offs, comparative advantage, and the market system

-   Lecture 3: Comparative advantage and the gains from international trade

-   Lecture 4: The interaction of demand and supply

-   Lecture 5:  Economic efficiency, government price setting, and tax externalities

-   Lecture 6:  Environmental policy and public goods

-   Lecture 7:  Elasticity-the responsiveness of demand and supply

-   Lecture 8:  Monopoly

**Section 2: Macroeconomics**

-   Lecture 9:  GDP-measuring total production and income

-   Lecture 10:  Unemployment and inflation

-   Lecture 11:  Economic growth, the financial system, and business cycles

-   Lecture 12:  Aggregate expenditure and output in the short run

-   Lecture 13:  Aggregate demand and aggregate supply analysis

-   Lecture 14:  Money, banks, and the federal reserve system monetary policy

-   Lecture 15:  Overview the government spending and tax multipliers

[**Textbooks:**]{.underline}

1. Acemoglu, D., Laibson, D., and List, J. (2022). Economics (3rd Edition). Pearson Education.

2. Samuelson, P., and Nordhaus, W. (2020). Economics (20th Edition). McGraw-Hill Education.

3. Mankiw, N. (2024). Principles of Economics (10th Edition). Cengage Learning. 

## Environmental Economics

**Section 1: Foundation to Environmental Economics**

-   Lecture 1: The environment and economics

-   Lecture 2: Normative and positive economic analysis

-   Lecture 3: Social choice: Environmental protection

-   Lecture 4: Efficiency and markets

-   Lecture 5: Market failure: Public goods, public bads and externalities

-   Lecture 6: Making decisions about environmental programs

-   Lecture 7: Demand for environmental goods

-   Lecture 8: Hedonic price methods

**Section 2: Regulating Pollution**

-   Lecture 9: Regulating pollution

-   Lecture 10: Emission prices and fees

-   Lecture 11: Property rights

-   Lecture 12: Audits, enforcement and moral hazard

-   Lecture 13: Voluntary actions and agreements

**Section 3: Advanced Topics**

-   Lecture 14: Managing risk and uncertainty

-   Lecture 15: Environment, growth and development

[**Textbooks:**]{.underline}

1.  Kolstad, C. (2011), Environmental economics (2nd Edition). New York : Oxford University Press.

2.  Tietenberg, T., and Lewis, L. (2019). Environmental and natural resource economics (11th Edition). Routledge.

## Economics of Public Policy 

**Section 1: Introduction and Background**

- Lecture 1: Introduction to public policy

- Lecture 2: Budget analysis and deficit financing

**Section 2: Externalities and Public Goods**

- Lecture 3: Externalities: Problems and solutions

- Lecture 4: Externalities in action: Environmental and health externalities

- Lecture 5: Public goods and cost-benefit analysis

- Lecture 6: State and local government expenditures

- Lecture 7: Education

**Section 3: Social Insurance and Redistribution**

- Lecture 8: Social insurance: The new function of government

- Lecture 9: Social security, unemployment insurance, disability insurance, and workers’ compensation

- Lecture 10: Health insurance I: Health economics and private health insurance

- Lecture 11: Health insurance II: Medicare, medicaid, and health care reform

- Lecture 12: Income distribution and welfare programs

**Section 4: Taxation in Theory and Practice**

- Lecture 13: Taxation: How it works and what it means

- Lecture 14: Taxation of business income

- Lecture 15: Fundamental tax reform and consumption taxation

[**Textbooks:**]{.underline}

1. Gruber, J. (2018). Public finance and public policy (6th Edition), Worth Publishers.

2. Stiglitz, J., and Rosengard, J. (2015). Economics of the public sector (6th Edition). WW Norton & Company.

## International Economics

**Section 1: Introduction to International Economics**

-   Lecture 1: Basics of international economics

-   Lecture 2: Introduction to international trade

-   Lecture 3: Reasons of international trade

-   Lecture 4: International trade models

**Section 2: International Trade Policy**

-   Lecture 5: The instruments of trade policy

-   Lecture 6: The political economy of trade policy

-   Lecture 7: Trade policy in developing countries: Part A

-   Lecture 8: Trade policy in developing countries: Part B

**Section 3: Open-economy Macroeconomics**

-   Lecture 9: Globalization, trade and environment

-   Lecture 10: Macroeconomic analysis of trade balance 

-   Lecture 11: National income accounting and the balance of payments

-   Lecture 12: Money, interest rates, exchange rates and the Federal Reserve

**Section 4: International Macroeconomic Policy**

-   Lecture 13: Economic geography

-   Lecture 14: Developing countries growth, crisis and reform

-   Lecture 15: International trade and biodiversity

[**Textbooks:**]{.underline}

1. Krugman, P., Obstfeld, M., and Melitz, M. (2018). International economics: Theory and policy. Boston: Pearson Education.

2. Krugman, P., Obstfeld, M., and Melitz, M. (2017). International trade: Theory and policy. Boston: Pearson Education.

3. Krugman, P., Obstfeld, M., and Melitz, M. (2018). International finance: Theory and policy. Boston: Pearson Education.

## Energy Economics

**Section 1: Economics of Energy**

-   Lecture 1: Energy overview

-   Lecture 2: Role of energy in the economy

-   Lecture 3: Energy markets, prices, and efficiency

-   Lecture 4: The economics of renewable energy

-   Lecture 5: Energy and economic growth

-   Lecture 6: Economic theory of the mine

**Section 2: Environmental and Natural Resource Economics**

-   Lecture 7: Oil and natural gas extraction and pricing

-   Lecture 8: Externalities and policy instruments

-   Lecture 9: The benefits and costs of environmental protection

**Section 3: Industrial Ecology**

-   Lecture 10: The changing landscape for global oil companies

-   Lecture 11: Carbon-neutral energy systems

-   Lecture 12: Global energy disparities

**Section 4: Energy Policy**

-   Lecture 13: International environmental agreements

-   Lecture 14: Energy efficiency: Puzzle and policies

-   Lecture 15: Energy policy consequences

[**Textbooks:**]{.underline}

1. Schwarz, P. (2021). Energy Economics. Routledge.

2. Zweifel, P., Praktiknjo, A., and Erdmann, G. (2017). Energy Economics: Theory and Applications. Springer.

3. Bhattacharyya, S. (2011). Energy Economics: Concepts, Issues, Markets, and Governance. Springer.

## Human Geography

**Section 1: Foundations of human geography**

- Lecture 1: Introduction to human geography

- Lecture 2: Population

- Lecture 3: Migration

- Lecture 4: Local culture, popular culture, and cultural landscapes

- Lecture 5: Identity: Race, ethnicity, gender and sexuality

- Lecture 6: Political geography

- Lecture 7: Urban geography

- Lecture 8: The humanized environment

**Section 2: Foundations of geographic plots in R and Python**

- Lecture 9: Processing shapefiles in R and Python

- Lecture 10: Basic maps with R and Python

**Section 3: Elegant geographic plots in R and Python**

- Lecture 11: Human geography of Africa

- Lecture 12: Human geography of Asia

- Lecture 13: Human geography of Australia

- Lecture 14: Human geography of Europe

- Lecture 15: Human geography of North America


[**Textbooks:**]{.underline}

1.  Fouberg, E., Murphy, A., and De Blij, H. (2020). Human geography: People, place, and culture. 12th edition. Wiley.

2.  Lovelace, R., Nowosad, J., and Muenchow, J. (2019). Geocomputation with R. CRC Press.

3.  Comber, L., and Brunsdon, C. (2020). Geographical data science and spatial data analysis: An Introduction in R. Sage.

## Future Design 

**Section 1: What is Future Design**

-   Lecture 1: Introduction to future design

-   Lecture 2: Future design: Combination of three academic disciplines

-   Lecture 3: Future design: From the perspective of economics

**Section 2: Future Design and Sustainable Development**

-   Lecture 4: Population growth and well-being

-   Lecture 5: The environment and economics

-   Lecture 6: The quality of the environment

-   Lecture 7: Globalization and the environment

-   Lecture 8: Market failure: Public goods, public bads and externalities

-   Lecture 9: Future failures: Disruption of C-cycle and N-cycle

**Section 3: Future Design and Public Policy**

-   Lecture 10: Public goods and cost-benefit analysis

-   Lecture 11: State and local government expenditures

-   Lecture 12: Income distribution and welfare programs

-   Lecture 13: The economics of biodiversity

-   Lecture 14: The economics of climate change

-   Lecture 15: Environmental goods valuation

[**Textbooks:**]{.underline}

1. Gruber, J. (2018). Public finance and public policy (6th Edition), Worth Publishers.

2. Stiglitz, J., and Rosengard, J. (2015). Economics of the public sector (6th Edition). WW Norton & Company.

3. Kolstad, C. (2011), Environmental economics (2nd Edition). New York : Oxford University Press.

Updated on: `r Sys.Date()`