---
title: "Linux"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Updated on: `r Sys.Date()`

# Partitioning hard drive

##### 1. Use `fdisk` command to delete a hard disk partition:

`fdisk` also known as format disk is a dialog-driven command in Linux used for creating and manipulating disk partition table. It is used for the view, create, delete, change, resize, copy and move partitions on a hard drive using the dialog-driven interface. `fdisk` allows you to create a maximum of four primary partitions and the number of logical partition depends on the size of the hard disk you are using. 

##### 2.  View All Disk Partitions:

The first thing to do before doing any thing with the disks and partition is to view basic details about all available partition in the system.

```{txt}
$ sudo fdisk -l
```

##### 3.  View Partition on a Specific Disk: 

Below command is used to view all disk partitions on device /dev/sda.

```{txt}
$ sudo fdisk -l /dev/sda
```

##### 4.  Delete a Hard Disk Partition:

To delete a partition for the hard disk and free up space occupied by that partition for example /dev/sda. Go to the command menu using following:

```{txt}
$ sudo fdisk /dev/sda
```

- And then type `d` to go to the delete partition menu. It will prompt the partition number you want to delete (type the number).

- Again type `d` to delete the specific partition.

- Run `w` command to write the changes and reboot the system.

- Continue this process until you delete all target partitions.

# Proxy in KUT

##### 1. Proxy for Ubuntu

```{txt}
$ sudo nano /etc/profile.d/proxy.sh
```

```{txt}
MY_PROXY_URL="proxy.noc.kochi-tech.ac.jp:3128"
HTTP_PROXY=$MY_PROXY_URL
HTTPS_PROXY=$MY_PROXY_URL
FTP_PROXY=$MY_PROXY_URL
http_proxy=$MY_PROXY_URL
https_proxy=$MY_PROXY_URL
ftp_proxy=$MY_PROXY_URL
export HTTP_PROXY HTTPS_PROXY FTP_PROXY http_proxy https_proxy ftp_proxy
```

```{txt}
$ sudo nano /etc/apt/apt.conf
```

```{txt}
Acquire::http::proxy "http://proxy.noc.kochi-tech.ac.jp:3128";
Acquire::https::proxy "http://proxy.noc.kochi-tech.ac.jp:3128";
Acquire::ftp::proxy "ftp://proxy.noc.kochi-tech.ac.jp:3128";
```

For curl

```{txt}
$ sudo nano ~/.curlrc
```

```{txt}
proxy=proxy.noc.kochi-tech.ac.jp:3128
```

For wget

```{txt}
$ sudo nano /etc/wgetrc
```

Add to the end

```{txt}
http_proxy = proxy.noc.kochi-tech.ac.jp:3128
https_proxy = proxy.noc.kochi-tech.ac.jp:3128
ftp_proxy = proxy.noc.kochi-tech.ac.jp:3128
```

##### 2. Proxy for Fedora

```{txt}
$ sudo nano /etc/profile.d/proxy.sh
```

```{txt}
MY_PROXY_URL="proxy.noc.kochi-tech.ac.jp:3128"
HTTP_PROXY=$MY_PROXY_URL
HTTPS_PROXY=$MY_PROXY_URL
FTP_PROXY=$MY_PROXY_URL
http_proxy=$MY_PROXY_URL
https_proxy=$MY_PROXY_URL
ftp_proxy=$MY_PROXY_URL
export HTTP_PROXY HTTPS_PROXY FTP_PROXY http_proxy https_proxy ftp_proxy
```

```{txt}
$ sudo nano /etc/dnf/dnf.conf
```

Add to the end

```{txt}
proxy=proxy.noc.kochi-tech.ac.jp:3128
```

For curl

```{txt}
$ sudo nano ~/.curlrc
```

```{txt}
proxy=proxy.noc.kochi-tech.ac.jp:3128
```

For wget

```{txt}
$ sudo nano /etc/wgetrc
```

Add to the end

```{txt}
http_proxy = proxy.noc.kochi-tech.ac.jp:3128
https_proxy = proxy.noc.kochi-tech.ac.jp:3128
ftp_proxy = proxy.noc.kochi-tech.ac.jp:3128
```

# STATA17 installation

First copy your **STATA17** source file in the **Downloads** folder of your PC. 

If the file is in **.zip** format, unzip to use it. Confirm that the **.tar.gz** extension file (Linux supported installation file) is located in the **Downloads** folder. 

I am assuming that you have the licence information ready in your hand during the following installation process:

##### Step 1: Create the installation directory, and change location into it

```{txt}
$ cd Downloads
```

```{txt}
$ mkdir statainstall
```

```{txt}
$ tar -xvzf Stata17Linux64.tar.gz -C statainstall
```

##### Step 2: Create the installation directory, and change location into it

```{txt}
$ sudo mkdir /usr/local/Stata17
```

```{txt}
$ cd /usr/local/Stata17
```

##### Step 3: Run the install script

```{txt}
$ sudo ~/Downloads/statainstall/install
```

Here, you will start the installation process and STATA17 will provide you the steps to complete. Follow these steps one by one and complete until the end.

##### Step 4: Configure the license file

```{txt}
$ sudo ./stinit
```

Again, STATA17 will ask you for several conformations and you need to respond properly.

##### Step 5: Running STATA17 with a graphical user interface using the command

```{txt}
$ ./xstata
```

- If you have a problem to execute the above code, you need to install `gtk2`
- You can install by:

```{txt}
$ sudo apt install gtk2 # For Ubuntu
$ sudo dnf install gtk2 # For Fedora
```

##### Step 6: Unity launcher and desktop file

- Even after successfully installing and running *Stata*, in Ubuntu/Fedora it won’t be available as an application in the dash, and it won’t have a proper icon in the application launcher. 

- To complete this step, you need a text editor. In this tutorial, I am using `gedit` which is the official text editor of the GNOME desktop environment. If your PC don't contain it, you can install easily by using terminal.

```{txt}
$ sudo apt install -y gedit # For Ubuntu
$ sudo dnf install -y gedit # For Fedora
```

- Then we can easily fix this by creating a **.desktop** file for *Stata*.

```{txt}
$ sudo gedit /usr/share/applications/stata17.desktop
```

- In this newly-created file just copy and paste the following, obviously adjusting it if you have a different version or flavor of *Stata*:

```{txt}
[Desktop Entry]
Version=17
Terminal=false
Icon=/usr/local/Stata17/stata17.png
Type=Application
Categories=Education;Scientific;
Exec=/usr/local/Stata17/xstata
Name=Stata/BE 17
Comment=Perform statistical analyses using Stata.
StartupNotify=true
MimeType=application/x-stata-dta;application/x-stata-do;application/x-stata-smcl;application/x-stata-stpr;application/x-stata-gph;application/x-stata-stsem;
Actions=doedit;use;view;graphuse;projmanag;semopen;
```

##### Step 7: Stata update process

- If SELinux is enabled in your PC, use following command to provide permission to your Stata to get updated. If SELinux is disabled, the following step is not necessary.

```{txt}
$ sudo chmod -R 777 '/usr/local/Stata17'
```

- If your internet connection is through a proxy server, add the proxy information inside your Stata to ensure update process as below.

```{txt}
a. Open Stata
b. Go to Preferences
c. General Preferences
d. Internet
e. add the proxy information. For KUT [proxy.noc.kochi-tech.ac.jp] and port [3128]
f. Go to Help
g. Update
```

# SELinux

SELinux (Security Enhanced Linux ) is a Linux kernel security module that allows administrators and users more control over access controls. It allows access based on SELinux policy rules. SELinux policy rules specify how processes and users interact with each other as well as how processes and users interact with files. When no SELinux policy rule explicitly allows access, such as for a process opening a file, access is denied.

SELinux has three modes:

- Enforcing: SELinux allows access based on SELinux policy rules.
- Permissive: SELinux only logs actions that would have been denied if running in enforcing mode.
- Disabled: No SELinux policy is loaded.

It is recommended to keep SELinux in enforcing mode, but in some cases, you may need to set it to a permissive mode or disable it completely. In this tutorial, I will show you how to disable SELinux on CentOS 7 systems.

##### 1. Check the SELinux Status

```{txt}
$ sestatus
```

Output

```{txt}
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      31
```

You can see from the output above that SELinux is enabled and set to enforcing mode.

##### 2. Disable SELinux

You can temporarily change the SELinux mode from targeted to permissive with the following command:

```{txt}
$ sudo setenforce 0
```

However, this change is valid for the current runtime session only. To permanently disable SELinux on your CentOS 7 system, follow the steps below:

##### 3. Pemanently Disable SELinux

3.1 Open the /etc/selinux/config file and set the SELINUX mod to disabled:

```{txt}
# This file controls the state of SELinux on the system.
# SELINUX= can take one of these three values:
#       enforcing - SELinux security policy is enforced.
#       permissive - SELinux prints warnings instead of enforcing.
#       disabled - No SELinux policy is loaded.
SELINUX=disabled
# SELINUXTYPE= can take one of these two values:
#       targeted - Targeted processes are protected,
#       mls - Multi Level Security protection.
SELINUXTYPE=targeted
```

3.2 Save the file and reboot your CentOS system with:

```{txt}
$ sudo shutdown -r now
```

3.3 Once the system boots up, verify the change with the sestatus command:

```{txt}
$ sestatus
```

The output should look like this:

```{txt}
SELinux status:                 disabled
```

# Gedit text editor

- `gedit` is the official text editor of the GNOME desktop environment. While aiming at simplicity and ease of use, `gedit` is a powerful general purpose text editor.

- Whether you are writing the next bestseller, programming an innovative application, or simply taking some quick notes, `gedit` will be a reliable tool to accomplish your task.

- Its flexible plugin system allows you to tailor the application to your needs and adapt it to your workflow.

- Install easily by using terminal.

```{txt}
$ sudo apt install -y gedit # For Ubuntu
$ sudo dnf install -y gedit # For Fedora
```

- Alternatively, snapd can be installed from the command line:

```{txt}
$ sudo apt install snapd # For Ubuntu
$ sudo snap install gedit
```

# Nano text editor

GNU nano (or we call it “nano”) is a simple terminal-based text editor. Some shortcuts include:

```{txt}
Ctrl + X to exit
Ctrl + O to write (or save as)
Alt + U to undo last action
```


