---
title: "News & Updates"
output:
  html_document:
    theme: darkly
    css: darkly_custom.css
    #toc: true
    toc_float: true
    collapsed: false
    number_sections: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```


- July 7–10, 2026: Presented my research titled "Accountability for Future Generations" at the Australian Conference of Economists (ACE 2026), University of Canberra, Canberra, Australia.

- May 16, 2026: Present my research activities titled “Future design social experiments” at the 29th Experimental Social Science Conference, Kochi University of Technology, Kochi, Japan.

- December 4, 2025: Participate in the 18th Medical-Engineering Collaboration Exchange Meeting 2025, Kochi University, Japan.

- September 20–21, 2025: Present my research titled “Can future design persistently improve indoor air quality?” at the 30th SEEPS Annual Conference, Musashi University, Tokyo, Japan.

- August 29–30, 2025: Present my paper “Can future design persistently improve indoor air quality?” at the Australian New Zealand Workshop in Experimental Economics (ANZWEE) 2025, hosted by Macquarie University, Sydney, Australia.

- August 29, 2025: Deliver an invited seminar at the School of Business Research Seminar Series 2025, University of Western Sydney, Australia.

- September 14–15, 2024: Present my research titled “Can future design persistently improve indoor air quality?” at the 29th SEEPS Annual Conference, Kansai University, Osaka, Japan.

- July 27–28, 2024: Present my research titled “Can future design persistently improve indoor air quality?” at the 8th International Symposium on Frontier Technology, Kochi University of Technology, Kami City, Kochi, Japan.

- December 18, 2023: Participate in the SEEPS Workshop 2023, Ito Campus, Kyushu University, Japan.

- December 9–10, 2023: Present my research activities titled “Future design social experiments” at the 17th Association of Behavioral Economics and Finance Conference, Kochi University of Technology, Kochi, Japan.

- November 16–18, 2022: Present my research titled “A future design workshop on inequality” at the 4th International Conference on Anticipation, Arizona State University, Tempe, Arizona, USA.

- January 29–30, 2022: Participate in Future Design 2022, Kochi University of Technology, Japan.

- October 14, 2021: Participate in the Q-AOS Symposium on Inclusive Growth, Kyushu University, Japan.

- September 28–29, 2019: Present my research titled “Growth potential for CO2 emissions transfer by United States-China trade battle” at the 24th SEEPS Annual Conference, Fukushima University, Fukushima, Japan.

- October 9–11, 2018: Participate in the Joint Tianjin University–Kyushu University Workshop on Economics, Tianjin University, Tianjin, China.

- July 22–25, 2018: Present my research titled “Natural capital of nations for sustainable development” at the 25th IPSA World Congress of Political Science, Brisbane, Australia.

- March 27–28, 2018: Participate in the Workshop on Sustainability, SDGs and Security, Inamori Center (A Hall), Ito Campus, Kyushu University, Japan.

- September 21–22, 2013: Present my research titled “Farmer’s adaptation strategy in Bangladesh” at the 18th SEEPS Annual Conference, Kobe University, Kobe, Japan.


Updated on: `r Sys.Date()`


