---
title: "Quarto"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Quarto within RStudio

RStudio includes support for editing and preview of Quarto documents. 

### YAML Intelligence

#### Documentation options

Document options are defined using YAML. For .qmd files, this YAML should appear at the start of the text file. For Jupyter notebooks, the YAML should appear as the first cell, which should be a raw cell. The first and last lines of this cell consist of three hyphens (---). Elements are specified as key:value pairs, and sub-elements are indented. Below you will find a host of document options you can edit in quarto.

##### Project options

```{txt}
---
project:  type: "default" # [default, website, book] type of output
execute-dir: "file" # [file, project] working directory for computations
output-dir: "output" # generate outputs (for instance, images, html, pdf) in this directory
---
```

##### Format options

```{txt}
---
format: pdf # [html, pdf, docx, odt, pptx, revealjs, beamer, gfm, commonmark, mediawiki, epub, ipynb] file format for the rendered document
---
```

There are many other output formats available than the ones listed in the comments above. The options available vary depending upon the format that is chosen.

##### Title and author

```{txt}
---
title: "Quarterly Marketing Funnel Performance" # Title of the document
date:  "2023-12-25" # The date shown on the document
author: "Mark Eting-Analyst" # Author(s) of the document
subtitle: "Analysis of leads" # Subtitle of the document
abstract: |
  We A/B tested the registration flow.
---
```

##### Styling

```{txt}
---
theme: "quartz" # {html, revealjs} ["default", "cerulean", "cosmo", ...] Name of a built-in HTML
                # Bootswatch theme, or link to a Sassy Cascading Style Sheets (SCSS) file
pdf-engine: "tinytex" # {pdf, beamer} Toolchain for generating the PDF
reference-doc: "template.docx" # {docx, odt, pptx} Path to a file to use as a style reference
quarto-required: ">= 1.2.0" # Oldest version of Quarto that will work correctly
---
```

##### Table of contents

```{txt}
---
toc: true # [false, true] Include a table of contents in the document
toc-depth: 2 # Least significant section header to include in table of contents
---
```

##### Section numbering

```{txt}
---
number-sections: true # [false, true] Should section headings be numbered?
number-depth: 2 # {html, pdf, docx, revealjs, beamer, epub} Least significant header to be numbered
---
```

##### Slides

```{txt}
---
incremental: true # {pptx, revealjs, beamer} [false, true] 
slide-level: 2 # {pptx, revealjs, beamer} What header level denotes a new slide
---
```

##### Fonts

```{txt}
---
mainfont: "Baskerville" # {html, pdf, beamer} Font family for regular
monofont: "JetBrains Mono" # {html, pdf, beamer} Font family for code
                           # Specify font families with CSS or LaTeX,
fontsize: 14 # {html, pdf, beamer} Set the base size of the font.
---
```

##### Colors

```{txt}
---
fontcolor: "#B06500" # {html} Color of text.
linkcolor: "#007FFF" # {html, pdf, beamer} Color of link text.
---
```

##### Layout

```{txt}
---
cap-location: "top" # ["top", "bottom", "margin"] Location of captions
                    # for figures and tables
papersize: "a4paper" # LaTeX paper size for the rendered document
                     # Common values: letterpaper (USA), a4paper (rest of world)
page-width: 8 # Width of page in rendered document
margin-top: 20px # Top margin for the page
---
```

##### Code

```{txt}
---
code-line-numbers: true # [false, true] 
highlight-style: "breeze" # ["default", "a11y", "arrow",..]
code-fold: "show" # [false, true, show]
code-overflow: "wrap" # ["scroll", "wrap"]
---
```

#### Execution options

##### Sub-elements

```{txt}
---
eval: false # [true, false] 
echo: false # [true, false] 
output: "asis" # [true, false, "asis"] 
warning: false # [true, false]
error: false # [true, false] 
include: false # [true, false] 
cache: false # [true, false, "refresh"] 
---
```

##### Figures

```{txt}
---
fig-width: 8 # Width for figures in inches
fig-height: 6 # Height for figures in inches
fig-format: "png" # File format for figures (Matplotlib or R graphics only)
fig-dpi: 300 # Figure resolution (Matplotlib or R graphics only)
fig-align: "center" # ["default", "left", "right", "center"] 
fig-cap-location: "bottom" # {html, pdf, revealjs, beamer} ["top", "bottom", "margin"] 
---
```

##### Tables

```{txt}
---
tbl-colwidths: [70, 30] # ["auto", true, false, <array>] Should tables wider than
                        # 72 characters have explicit column widths?
                        # "auto": Use Markdown column widths unless the column
                        # contains a hyperlink
                        # true: Always use markdown column widths
                        # false: Never use markdown table widths
                        # <array>: Column widths as the %age of table width
tbl-cap-location: "margin" # {html, pdf, revealjs, beamer} ["top", "bottom", "margin"] Location of figure captions
---
```

##### Links

```{txt}
---
link-external-newwindow: true # [false, true] Open external pages in new browser tab?
---
```

##### References

```{txt}
---
bibliography: "refs.bib" # Path to BibTeX/Citation Style Language bibliography file
---
```

#### Generate document

##### Preview

While authoring your document, use the preview to quickly see its current state. The generated preview will open in a browser. Consider having your Jupyter notebook, IDE, or text editor and the preview visible on-screen at the same time.

Open a terminal

```{txt}
$ quarto preview document_name
```

##### Rendering

Once you have finished authoring your document, you can render the final version.

Open a terminal

```{txt}
$ quarto render document_name
```

This will create rendered documents in the file formats specified in the YAML header. 
To override the file format, use the following command variant:

```{txt}
$ quarto render document_name --to {format} # [pdf, html, docx]
```

# Quarto within JupyterLab

Quarto can render `JupyterLab` represented as plain text (`.qmd`) or as a normal notebook file (`.ipynb`). One benefit of using `.ipynb` is that you can use `JupyterLab` as your editor.

#### YAML Front Matter

The first cell of your notebook should be a `Raw` cell that contains the document title, author, and any other options you need to specify. Note that you can switch the type of a cell to Raw using the notebook toolbar:

```{txt}
---
title: "Python for Data Science"
author: "Moinul Islam"
date: "4/30/2024"
format: 
  html:
    code-fold: FALSE
jupyter: python3
---
```

Note that we’ve added the jupyter: python3 option to the `YAML` front matter to indicate which `Jupyter kernel` to render with. You would render this document with:

```{txt}
quarto render basics-jupyter.qmd
```

#### Converting notebooks

You can convert between `.ipynb` and `.qmd` representations of a notebook using the quarto convert command. For example:

```{txt}
quarto convert basics-jupyter.ipynb # converts to .qmd
quarto convert basics-jupyter.qmd   # converts to .ipynb
```

#### Render without preview

```{txt}
quarto render notebook.ipynb
quarto render notebook.ipynb --to docx
quarto render notebook.ipynb --to pdf
```

#### Cell Execution

When rendering an `.ipynb` Quarto will not execute the cells within the notebook by default. If we want to execute the cells we can pass the `--execute` flag to render:

```{txt}
quarto render notebook.ipynb --execute
```

#### JupyterLab extension

The Quarto `JuptyerLab` extension enables `JupyterLab` which use Quarto markdown to properly display the contents of the markdown cells. 

```{txt}
python3 -m pip install jupyterlab-quarto  # Mac
py -m pip install jupyterlab-quarto  # Windows
```

Updated on: `r Sys.Date()`