---
title: "Research"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

## Journal articles (peer-review)

1.  Sharofiddinov, H., **Islam, M.**, Kotani, K. (2025). Adaptation indicator to climate change and farm sizes in agriculture: A reflection of farming culture and history. *Ecological Indicators*, (forthcoming). [Q1]

2.  **Islam, M.**, Kotani, K., and Managi, S. (2024). Nature dependence and seasonality change perceptions for climate adaptation and mitigation. *Economic Analysis and Policy*, 81, 34--44. [Q1] (<https://doi.org/10.1016/j.eap.2023.11.001>)

3.  Sharofiddinov, H., **Islam, M.**, Kotani, K. (2024). How does the number of water users in a land reform matter for water availability in agriculture? *Agricultural Water Management*, 293, 108677. [Q1] (<https://doi.org/10.1016/j.agwat.2024.108677>)

4.  Managi, S., **Islam, M.\*** , Zhang, D., Zaied, Y., and Saito, O. (2023). Natural capital accounting for sustainable cities. *Sustainability Science*, 18, 2049--2051. [Q1] (<https://doi.org/10.1007/s11625-023-01356-7>)

5.  Yamaguchi, R., **Islam, M.**, and Managi, S. (2023). Natural capital and wealth accounting for sustainability assessment: A global perspective. *International Review of Environmental and Resource Economics*, 16, 431--465. [Q2] (<http://dx.doi.org/10.1561/101.00000148>)

6.  **Islam, M.**, Zhang, B., and Managi, S. (2022). The trade-off between natural capital and other capitals in Pakistan. *Sustainability Science*, 17, 1799--1811. [Q1] (<https://doi.org/10.1007/s11625-022-01143-w>)

7.  Managi, S., **Islam, M.\*** , Saito, O. et al. (2022). Valuation of nature and nature's contributions to people. *Sustainability Science*, 17, 701--705. [Q1] (<https://doi.org/10.1007/s11625-022-01140-z>)

8.  **Islam, M.**, and Managi, S. (2022). Valuation of nature's contribution in Ladakh, India: An inclusive wealth method. *Sustainability Science*, 17, 905--918. [Q1] (<https://doi.org/10.1007/s11625-021-01030-w>)

9.  N'dri, L., **Islam, M.\*** , and Kakinaka, M. (2021). ICT and environmental sustainability: Any differences in developing countries? *Journal of Cleaner Production*, 297, 126642. [Q1] (<https://doi.org/10.1016/j.jclepro.2021.126642>)

10. Badamvaanchig, M., **Islam, M.\*** , and Kakinaka, M. (2021). Pass-through of commodity price to Mongolian stock price: Symmetric or asymmetric? *Resources Policy*, 70, 101955. [Q1] (<https://doi.org/10.1016/j.resourpol.2020.101955>)

11. Hongsakhone, S., **Islam, M.\*** , and Ichihashi, M. (2021). Producing a village input-output table (VIOT) from household survey data: A case study of a VIOT for a rural village in northern Lao PDR. *Journal of Economic Structures*, 10, 1--24. (<https://doi.org/10.1186/s40008-020-00231-3>)

12. Sharifi, A., Simangan, D., Lee, C., Reyes, S., Katramiz, T., Josol, J., and **Islam, M.** (2021). Climate-induced stressors to peace: A review of recent literature. *Environmental Research Letters*, 16, 073006. [Q1] (<https://doi.org/10.1088/1748-9326/abfc08>)

13. Simangan, D., Virji, H., Hendrix, C., **Islam, M.**, Kaneko, S., Ma, Y., Mechler, R., Pangotra, P., Peters, K., Sharifi, A. and Shams, S. (2021). A co-designed heuristic guide for investigating the peace-sustainability nexus in the context of global change. *Sustainability Science*, 16, 1097--1109. [Q1] (<https://doi.org/10.1007/s11625-021-00970-7>)

14. Essandoh, O. K., **Islam, M.\*** , and Kakinaka, M. (2020). Linking international trade and foreign direct investment to $CO_2$ emissions: Any differences between developed and developing countries? *Science of The Total Environment*, 712, 136437. [Q1] (<https://doi.org/10.1016/j.scitotenv.2019.136437>)

15. Jingyu, W., Yuping B., Yihzong W., Zhihui L., Xiangzheng D., **Islam M.**, and Managi S. (2020). Measuring inclusive wealth of China: Advances in sustainable use of resources. *Journal of Environmental Management*, 264, 110328. [Q1] (<https://doi.org/10.1016/j.jenvman.2020.110328>)

16. Hotak, S., **Islam, M.\*** , Kakinaka, M. and Kotani, K. (2020). Carbon emissions and carbon trade balances: International evidence from panel ARDL analysis. *Environmental Science and Pollution Research*, 27, 24115--24128. [Q1] (<https://doi.org/10.1007/s11356-020-08478-w>)

17. Coulibaly, T., **Islam, M.**, and Managi, S. (2020). The Impacts of climate change and natural disasters on agriculture in African countries. *Economics of Disasters and Climate Change*, 4, 347--363. (<https://doi.org/10.1007/s41885-019-00057-9>)

18. Coulibaly, T., Wakamatsu, M., **Islam, M.**, Fukai, H., Managi, S. and Zhang, B. (2020). Differences in water policy efficacy across South African water management areas. *Ecological Economics*, 175, 106707. [Q1] (<https://doi.org/10.1016/j.ecolecon.2020.106707>)

19. **Islam, M.**, and Managi, S. (2019). Green growth and pro-environmental behavior: Sustainable resource management using natural capital accounting in India. *Resources, Conservation and Recycling*, 145, 126--138. [Q1] (<https://doi.org/10.1016/j.resconrec.2019.02.027>)

20. Managi, S., **Islam, M.**, Saito, O., Stenseke, M., Dziba, L., Lavorel, S., Pascual, U., and Hashimoto, S. (2019). Valuation of nature and nature's contributions to people. *Sustainability Science*, 1463--1465. [Q1] (<https://doi.org/10.1007/s11625-019-00732-6>)

21. **Islam, M.**, Kanemoto, K., and Managi, S. (2019). Growth potential for $CO_2$ emissions transfer by tariff reduction. *Environmental Research Letters*, 14, 024011. [Q1] (<https://iopscience.iop.org/article/10.1088/1748-9326/aaf688/meta>)

22. Yamaguchi, R., **Islam, M.**, and Managi, S. (2019). Inclusive wealth in the 21st century. *Letters in Spatial and Resource Sciences*, 12, 101--111. [Q2] (<https://doi.org/10.1007/s12076-019-00229-x>)

23. Ying Lee, C., Lotsu, S., **Islam, M.\*** , Yoshida, Y., and Kaneko, S. (2019). The Impact of an energy efficiency improvement policy on the economic performance of electricity-intensive firms in Ghana. *Energies*, 12, 3684. [Q3] (<https://doi.org/10.3390/en12193684>)

24. **Islam, M.**, Yamaguchi, R., Sugiawan, Y., and Managi, S. (2018). Valuing natural capital and ecosystem services: A literature review. *Sustainability Science*, 14, 159-174. [Q1] (<https://doi.org/10.1007/s11625-018-0597-7>)

25. **Islam, M.**, and Managi, S. (2018). Sustainable adaptation to multiple water risks in agriculture: Evidence from Bangladesh. *Sustainability* (Switzerland), 10, 1734. [Q2] (<https://doi.org/10.3390/su10061734>)

26. Rajapaksa, D., **Islam, M.**, and Managi, S. (2018). Pro-environmental behavior: The role of public perception in infrastructure and the social factors for sustainable development. *Sustainability* (Switzerland), 10, 937. [Q2] (<https://doi.org/10.3390/su10040937>)

27. Tolliver, C., **Islam, M.**, Shin, K., and Managi, S. (2018). The impact of energy security risks on energy consumption. *International Journal of Innovation and Sustainable Development*, 12, 258--270. [Q4] (<https://doi.org/10.1504/IJISD.2018.091522>)

28. Sugiawan, Y., **Islam, M.**, and Managi, S. (2017). Global marine fisheries with environmental sustainability. *Economic Analysis and Policy*, 55, 158--168. [Q1] (<https://doi.org/10.1016/j.eap.2017.08.004>)

29. Rajapaksa, D., **Islam, M.**, and Managi, S. (2017). Natural capital depletion: The impact of natural disasters on inclusive growth. *Economics of Disasters and Climate Change*, 1, 233--244. (<https://doi.org/10.1007/s41885-017-0009-y>)

30. **Islam, M.**, Kanemoto, K., and Managi, S. (2016). Impact of trade openness and sector trade on embodied greenhouse gases emissions and air pollutants. *Journal of Industrial Ecology*, 20, 494--505. [Q1] (<https://doi.org/10.1111/jiec.12455>)

31. **Islam, M.**, Kotani, K., and Managi, S. (2016). Climate perception and flood mitigation cooperation: A Bangladesh case study. *Economic Analysis and Policy*, 49, 117--133. [Q1] (<https://doi.org/10.1016/j.eap.2016.01.001>)

32. **Islam, M.**, and Kotani, K. (2016). Changing seasonality in Bangladesh. *Regional Environmental Change*, 16, 585--590. [Q2] (<https://doi.org/10.1007/s10113-015-0758-5>)

## Policy reports (peer-review)

1.  Inclusive wealth report 2023. United Nation Environmental Program (UNEP). [link](https://wedocs.unep.org/handle/20.500.11822/43131)

2.  Inclusive wealth of Pakistan: The case for investing in natural capital and restoration (2021). United Nation Environmental Program (UNEP). [link](https://www.unep.org/resources/report/inclusive-wealth-pakistan-case-investing-natural-capital-and-restoration)

3.  Future design: For the survival of humankind (2022). Think7: Research-based policy recommendations for the G7. [link](https://www.think7.org/publication/future-design/)

## Book chapters (peer-review)

1.  **Islam, M.**, and Managi, S. (2021). Global human capital: View from inclusive wealth. In measuring human capital (pp. 39-54). Academic Press. ISBN: 9780128190579. [link](https://www.elsevier.com/books/measuring-human-capital/fraumeni/978-0-12-819057-9)

2.  Sugiawan, Y., **Islam, M.**, and Managi, S. (2019). Global marine fisheries with environmental sustainability. In wealth, inclusive growth and sustainability. Routledge, New York, USA. [link](https://www.taylorfrancis.com/chapters/edit/10.4324/9780429400636-6/global-marine-fisheries-economic-growth-yogi-sugiawan-moinul-islam-shunsuke-managi?context=ubx&refId=112be11e-7960-46c1-b5ad-5e7409f6d1df)

3.  Sankaralingam, I., **Islam, M.**, Nozawa, W., and Managi, S. (2019). Impact of infrastructure in India. In wealth, inclusive growth and sustainability. Routledge, New York, USA. [link](https://www.taylorfrancis.com/chapters/edit/10.4324/9780429400636-3/impact-infrastructure-india-iswarya-sankaralingam-moinul-islam-wataru-nozawa-shunsuke-managi?context=ubx&refId=63941a90-93ea-4df3-8df1-da2895e4a04e)

4.  Jumbri, I., **Islam, M.**, and Managi, S. (2019). Inclusive wealth adjusted by total factor productivity as a sustainable measurement: global productivity analysis. In wealth, inclusive growth and sustainability. Routledge, New York, USA. [link](https://www.taylorfrancis.com/chapters/edit/10.4324/9780429400636-7/inclusive-wealth-adjusted-total-factor-productivity-sustainability-measurement-isma-addi-jumbri-moinul-islam-shunsuke-managi?context=ubx)

5.  Coulibaly, T., **Islam, M.**, and Managi, S. (2019). The impact of climate change and extreme events on agriculture in Africa. In wealth, inclusive growth and sustainability. Routledge, New York, USA. [link](https://www.taylorfrancis.com/chapters/edit/10.4324/9780429400636-11/impact-climate-change-extreme-events-agriculture-africa-thierry-coulibaly-moinul-islam-shunsuke-managi?context=ubx)

6.  Qiuyi, C., **Islam, M.**, and Managi, S. (2019). Human capital change and social impact under China's universal two-child policy. In wealth, inclusive growth and sustainability. Routledge, New York, USA. [link](https://www.taylorfrancis.com/chapters/edit/10.4324/9780429400636-16/human-capital-change-social-impact-china-universal-two-child-policy-qiuyi-chen-moinul-islam-shunsuke-managi?context=ubx)

7.  Mahful, R., **Islam, M.**, Nakayam, H., and Managi, S. (2019). The effect of landfill gas emission on global warming and workers' health in Indonesia. In wealth, inclusive growth and sustainability. Routledge, New York, USA. [link](https://www.taylorfrancis.com/chapters/edit/10.4324/9780429400636-15/effect-landfill-gas-emission-global-warming-workers-health-indonesia-rafid-mahful-moinul-islam-hirofumi-nakayama-shunsuke-managi?context=ubx)

## International conferences

1.  **Islam, M.** Can future design persistently improve indoor air quality?, The 29th SEEPS Annual Conference, Kansai University, Osaka, Japan, 14--15 September, 2024.

2.  **Islam, M.** Can future design persistently improve indoor air quality?, The 8th International Symposium on Frontier Technology, Kochi University of Technology, Kami city, Kochi, Japan, 27--28 July, 2024.

3.  **Islam, M.** Future design social experiments, The 17th Association of Behavioral Economics and Finance Conference, Kochi city, Kochi, Japan, 9--10 December, 2023.

4.  **Islam, M.** A future design workshop on inequality, The 4th International Conference on Anticipation, Tempe, Arizona, USA, 16--18 November, 2022.

5.  **Islam, M.** Growth potential for $CO_2$ emissions transfer by United States-China trade battle, The 24th SEEPS Annual Conference, Fukushima University, Fukushima, Japan, 28--29 September, 2019.

6.  **Islam, M.** Natural capital of nations for sustainable development, The 25th IPSA World Congress of Political Science, Brisbane, Australia, 22--25 July, 2018.

7.  **Islam, M.** Farmer's adaptation strategy in Bangladesh, The 18th SEEPS Annual Conference, Kobe University, Kobe, Japan, 21--22 September, 2013.

## International symposiums

1.  SEEPS workshop 2023, Ito campus, Kyushu University, Japan, 18 December, 2023.

2.  Future Design 2022, Kochi University of Technology, Japan, 29 -- 30 January 2022.

3.  Q-AOS Symposium on Inclusive Growth, Kyushu University, Japan, 14 October 2021.

4.  Joint Tianjin University-Kyushu University workshop on economics, Tianjin University, Tianjin, China, 9 -- 11 October 2018.

5.  Workshop on Sustainability, SDGs and Security, Inamori Center (A Hall), Ito campus, Kyushu University, Japan, 27 -- 28 March 2018.

## Research grants

1.  Grants-in-Aid for Scientific Research from the Japanese government. Category: Grant-in-Aid for Early-Career Scientists. Principal investigator: **Moinul Islam**. Grant number: 21K13290. Project period: 2021/04 -- 2025/03.

2.  Grants-in-Aid for Scientific Research from the Japanese government. Category: Fund for the Promotion of Joint International Research [Fostering Joint International Research (B)]. Principal Investigator: Koji Kotani. Co-investigator: Makoto Kakinaka, **Moinul Islam**, Kostiantyn Ovsiannikov, Yuta Yasui. Grant number: 22KK0020. Project period: 2022/10 -- 2027/03.

3.  Grants-in-Aid for Scientific Research from the Japanese government. Category: Grant-in-Aid for Research Activity Start-up. Principal investigator: **Moinul Islam**. Grant number: 19K24384. Project period: 2019/04 -- 2021/03.

## Professional service

##### Guest editor

-   [1] Sustainability Science (Springer).

##### Peer reviewer

-   [1] Sustainability Science (Springer), [2] Economic Analysis and Policy (Elsevier), [3] Journal of Cleaner Production (Elsevier), [4] Environmental Research Letters (IOPScience), [5] Environmental Science and Pollution Research (Springer), [6] Journal of Behavioral and Experimental Economics (Elsevier), [7] Global Sustainability (Cambridge University Press), [8] IEEE Transactions on Engineering Management (Engineering Management Review), [9] Sustainability (MDPI), [10] Economics of Disasters and Climate Change (Springer), [11] Environmental Economics and Policy Studies (Springer), [12] Plos One (Public Library of Science).

## Working papers

1.  Rahman, M., Asma, K., **Islam, M.**, Saijo, T., and Kotani, K. Does future design induce people to make a persistent change to sustainable food consumption?, Working Papers [SDES-2024-4](http://www.souken.kochi-tech.ac.jp/seido/wp/SDES-2024-4.pdf), Kochi University of Technology, School of Economics and Management, 2024.

2.  Husniddin, S., **Islam, M.**, and Kotani, K. Farm sizes and adaptation responses to climate change in agriculture: A reflection of Tajikistan’s farming culture and history. Working Papers [SDES-2024-2](http://www.souken.kochi-tech.ac.jp/seido/wp/SDES-2024-2.pdf), Kochi University of Technology, School of Economics and Management, 2024.

3.  Husniddin, S., **Islam, M.**, and Kotani, K. How does the number of water users in a land reform matter for irrigation water availability? Working Papers [SDES-2023-5](http://www.souken.kochi-tech.ac.jp/seido/wp/SDES-2023-5.pdf), Kochi University of Technology, School of Economics and Management, 2023.

4.  Husniddin, S., **Islam, M.**, and Kotani, K. Does the reorganization of large agricultural farms decrease irrigation water availability? A case study of Tajikistan, Working Papers [SDES-2022-3](http://www.souken.kochi-tech.ac.jp/seido/wp/SDES-2022-3.pdf), Kochi University of Technology, School of Economics and Management, 2022.

5.  **Islam, M.**, and Kotani, K. Who perceive seasonality change? A case of the Meghna basin, Bangladesh, Working Papers [SDES-2020-15](http://www.souken.kochi-tech.ac.jp/seido/wp/SDES-2020-15.pdf), Kochi University of Technology, School of Economics and Management, 2020.

6.  **Islam, M.**, and Kotani, K. Six or four seasons? An evidence for seasonal change in Bangladesh, Working Papers [SDES-2014-11](http://www.souken.kochi-tech.ac.jp/seido/wp/SDES-2014-11.pdf), Kochi University of Technology, School of Economics and Management, 2014.

7.  **Islam, M.**, and Kotani, K. Six or four seasons? Perceptions of climatic changes and people's cooperative attitudes toward food protection in Bangladesh. Working Paper [EMS-2013-06](https://www.iuj.ac.jp/research/workingpapers/EMS_2013_06.pdf), International University of Japan, Economics & Management Series, 2013.

## Scholarly memberships

1.  Society for Environmental Economics and Policy Studies (SEEPS)

2.  Association of Environmental and Resource Economists (AERE)

Updated on: `r Sys.Date()`
