---
title: "Stata"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# STATA17 installation in Linux

First copy your **STATA17** source file in the **Downloads** folder of your PC.

If the file is in **.zip** format, unzip to use it. Confirm that the **.tar.gz** extension file (Linux supported installation file) is located in the **Downloads** folder.

I am assuming that you have the licence information ready in your hand during the following installation process:

##### Step 1: Create the installation directory, and change location into it

```{txt}
$ cd Downloads
```

```{txt}
$ mkdir statainstall
```

```{txt}
$ tar -xvzf Stata17Linux64.tar.gz -C statainstall
```

##### Step 2: Create the installation directory, and change location into it

```{txt}
$ sudo mkdir /usr/local/Stata17
```

```{txt}
$ cd /usr/local/Stata17
```

##### Step 3: Run the install script

```{txt}
$ sudo ~/Downloads/statainstall/install
```

Here, you will start the installation process and STATA17 will provide you the steps to complete. Follow these steps one by one and complete until the end.

##### Step 4: Configure the license file

```{txt}
$ sudo ./stinit
```

Again, STATA17 will ask you for several conformations and you need to respond properly.

##### Step 5: Running STATA17 with a graphical user interface using the command

```{txt}
$ ./xstata
```

-   If you have a problem to execute the above code, you need to install `gtk2`
-   You can install by:

```{txt}
$ sudo apt install gtk2 # For Ubuntu
$ sudo dnf install gtk2 # For Fedora
```

##### Step 6: Unity launcher and desktop file

-   Even after successfully installing and running *Stata*, in Ubuntu/Fedora it won’t be available as an application in the dash, and it won’t have a proper icon in the application launcher.

-   To complete this step, you need a text editor. In this tutorial, I am using `gedit` which is the official text editor of the GNOME desktop environment. If your PC don't contain it, you can install easily by using terminal.

```{txt}
$ sudo apt install -y gedit # For Ubuntu
$ sudo dnf install -y gedit # For Fedora
```

-   Then we can easily fix this by creating a **.desktop** file for *Stata*.

```{txt}
$ sudo gedit /usr/share/applications/stata17.desktop
```

-   In this newly-created file just copy and paste the following, obviously adjusting it if you have a different version or flavor of *Stata*:

```{txt}
[Desktop Entry]
Version=17
Terminal=false
Icon=/usr/local/Stata17/stata17.png
Type=Application
Categories=Education;Scientific;
Exec=/usr/local/Stata17/xstata
Name=Stata/BE 17
Comment=Perform statistical analyses using Stata.
StartupNotify=true
MimeType=application/x-stata-dta;application/x-stata-do;application/x-stata-smcl;application/x-stata-stpr;application/x-stata-gph;application/x-stata-stsem;
Actions=doedit;use;view;graphuse;projmanag;semopen;
```

##### Step 7: Stata update process

-   If SELinux is enabled in your PC, use following command to provide permission to your Stata to get updated. If SELinux is disabled, the following step is not necessary.

```{txt}
$ sudo chmod -R 777 '/usr/local/Stata17'
```

-   If your internet connection is through a proxy server, add the proxy information inside your Stata to ensure update process as below.

```{txt}
a. Open Stata
b. Go to Preferences
c. General Preferences
d. Internet
e. add the proxy information. For KUT [proxy.noc.kochi-tech.ac.jp] and port [3128]
f. Go to Help
g. Update
```

# Descriptive Statistics

-   `describe`: describe produces a summary of the dataset in memory or of the data stored in a Stata-format dataset.

```{txt}
describe [varlist] 
```

-   `count`: counts the number of observations

```{txt}
count 
```

-   `sum`: shows number of observations, mean, min & max of all/some vars

```{txt}
sum 
```

# Social experiment data analysis

Nomenclature:

C: Control group

T: Treatment group

#### Step 1: Summary statistics for C and T1 
(when we have the data for three rounds: pre-treatment, post-treatment-1 and post-treatment-2 captured by time 1, time 2 and time 3, respectively)

##### Independent variables

We assume that there should not be any differences between C and T1 at pre-treatment round.

```{txt}
tabstat [var-n], statistics(mean median sd count), if group==0 & time==1

tabstat [var-n], statistics(mean median sd count), if group==1 & time==1

tabstat [var-n], statistics(mean median sd count), if time==1
```

##### Dependent variables

We assume that there should be differences between C and T1 in post-treatment rounds compared to pre-treatment round.

```{txt}
tabstat [var-n] , statistics(mean median sd min max count), if group==0 & time==1

tabstat [var-n] , statistics(mean median sd min max count), if group==1 & time==1

tabstat [var-n] , statistics(mean median sd min max count), if group==0 & time==2

tabstat [var-n] , statistics(mean median sd min max count), if group==1 & time==2

tabstat [var-n] , statistics(mean median sd min max count), if group==0 & time==3

tabstat [var-n] , statistics(mean median sd min max count), if group==1 & time==3

tabstat [var-n] , statistics(mean median sd min max count)
```

#### Step 2: C and T1 have no differences

Statistical test to check that in pre-treatment round, C and T1 have no significant differences

##### `Chi2` test

The chi-square analysis is a useful and relatively flexible tool for determining if categorical variables are related. To run a chi-square for independence, we can use the `tabulate` command. The output is simple: we are given a table of observed frequencies, followed by the chi-square value and p-value

```{txt}
tabulate [var-1] group, chi2, if time==1
```

##### `Mann-Whitney` test

A non-parametric test that is used to compare two sample means that come from the same population, and used to test whether two sample means are equal or not.  Usually, the Mann-Whitney U test is used when the data is ordinal or when the assumptions of the t-test are not met.

```{txt}
ranksum [var-1], by(group), if time==1
```

Updated on: `r Sys.Date()`