---
title: 'Geoinformation'
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Policymakers and researchers are increasingly interested in using experimental methods to inform the design of social policy. The use of economic experiments to test economic policies has accelerated in recent years. They are not simulations or role-playing exercises. They involve real people who make serious choices. In an economic experiment, to bridge the gap between a theory and an actual economic policies that solves fundamental social problems, it is important to observe and evaluate the performance of an **institution (mechanism)** in the context of actual decisions faced by real people.

# Geoinformation mechanism

I establish **geoinformation mechanism** through which I aim to suggest improvements in climate change adaptation and natural disasters mitigation. In this mechanism, I will incorporate geoinformation to enhance existing climate change and natural disasters adaptation strategies by leveraging advancements in information and communication technology. Through this **geoinformation mechanism**, I aim to reduce vulnerability and the costs associated with climate change and natural disasters. I am now developing an experimental design to implement **geoinformation mechanism** in experimental economics and environmental economics.

Updated on: `r Sys.Date()`